import { CITIES, SEASONS, altitude, noonAltitude, shadowLength, daylight, solarAzimuth, clock, duration, shadowText, sunState } from './science.js';
import { QUIZ, MISSIONS } from './curriculum.js';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const KEY='hajun-sun-lab-v1';
const fresh=()=>({missions:[],mastered:[],wrong:[],gameBest:0,notes:[],sound:false});
let progress=fresh(),storageOK=true;
try {
  const raw=JSON.parse(localStorage.getItem(KEY)||'null');
  if(raw&&typeof raw==='object') {
    for(const k of ['missions','mastered','wrong']) progress[k]=[...new Set(Array.isArray(raw[k])?raw[k]:[])].filter(id=>(k==='missions'?MISSIONS:QUIZ).some(q=>q.id===id));
    progress.gameBest=Math.max(0,Math.min(5,Number(raw.gameBest)||0)); progress.sound=raw.sound===true;
    progress.notes=(Array.isArray(raw.notes)?raw.notes:[]).filter(n=>n&&CITIES[n.city]&&SEASONS[n.season]&&Number.isFinite(n.time)&&n.time>=4&&n.time<=20&&[.5,1,1.5,2].includes(n.height)&&typeof n.id==='string').slice(-20);
  }
}catch{storageOK=false;}
let tab='lab', city='daegu', season='spring', time=9, height=1, showAngle=true, activeMission=0, lastMissionMessage='',energyAngle=55,tilt=true;
let playing=false,raf=0,lastFrame=0,toastTimer,installPrompt=null,audioContext=null;
let quizSession=null;
let game={round:0,guess:45,submitted:false,stars:0,done:false,targets:[30,65,45,75,20]};
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const f=n=>Number(n).toFixed(1);
function save(){try{localStorage.setItem(KEY,JSON.stringify(progress));storageOK=true;}catch{storageOK=false;}updateHeader();}
function updateHeader(){
  $('#xp').textContent=`✧ ${progress.missions.length*20+progress.mastered.length*10+progress.gameBest*10} XP`;
  $('#sound').setAttribute('aria-pressed',String(progress.sound));$('#sound').setAttribute('aria-label',progress.sound?'소리 끄기':'소리 켜기');$('#sound').title=progress.sound?'소리 끄기':'소리 켜기';
  $('#storage-status').textContent=storageOK?'학습 기록은 이 기기의 브라우저에 저장돼요. 기기·브라우저를 바꾸면 기록이 이어지지 않아요.':'브라우저 저장 공간을 사용할 수 없어. 지금 학습은 가능하지만 창을 닫으면 기록이 사라질 수 있어.';
}
function toast(message){clearTimeout(toastTimer);$('#toast').textContent=message;$('#toast').classList.add('show');toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),4200);}
function modal(title,body){pause();$('#dialog-content').innerHTML=`<h2 id="dialog-title">${title}</h2>${body}`;if(!$('#dialog').open)$('#dialog').showModal();}
function chime(kind='correct'){
  if(!progress.sound)return;
  try {const A=window.AudioContext||window.webkitAudioContext;if(!A)return;audioContext??=new A();audioContext.resume();const notes=kind==='retry'?[330,294]:kind==='win'?[523,659,784,1047]:[659,880];notes.forEach((freq,i)=>{const osc=audioContext.createOscillator(),g=audioContext.createGain();osc.connect(g);g.connect(audioContext.destination);osc.frequency.value=freq;const t=audioContext.currentTime+i*.12;g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(.09,t+.01);g.gain.exponentialRampToValueAtTime(.001,t+.2);osc.start(t);osc.stop(t+.22);osc.onended=()=>{osc.disconnect();g.disconnect();};});}catch{}
}
function speak(text){
  if(!('speechSynthesis'in window)){toast('이 브라우저에서는 읽어 주기를 지원하지 않아. 화면 설명으로 공부할 수 있어.');return;}
  progress.sound=true;save();window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='ko-KR';u.rate=.9;const voice=window.speechSynthesis.getVoices().find(v=>v.lang.startsWith('ko'));if(voice)u.voice=voice;u.onerror=e=>{if(!['canceled','interrupted'].includes(e.error))toast('기기의 한국어 음성과 미디어 음량을 확인해 줘.');};window.speechSynthesis.speak(u);
}
function confetti(){if(window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;const box=$('#confetti');box.innerHTML='';for(let i=0;i<32;i++){const p=document.createElement('i');p.className='confetti-piece';p.style.left=`${Math.random()*100}%`;p.style.background=['#ffce62','#8fb786','#5e9f94','#e4a69d'][i%4];p.style.animationDelay=`${Math.random()*.4}s`;box.append(p);}setTimeout(()=>box.innerHTML='',2400);}
function sunFace(x,y,r=27){return `<g transform="translate(${x} ${y})"><g stroke="#efba45" stroke-width="3" stroke-linecap="round">${Array.from({length:12},(_,i)=>`<path d="M${Math.cos(i*Math.PI/6)*(r+9)} ${Math.sin(i*Math.PI/6)*(r+9)} L${Math.cos(i*Math.PI/6)*(r+17)} ${Math.sin(i*Math.PI/6)*(r+17)}"/>`).join('')}</g><circle r="${r+5}" fill="#ffe9a2" opacity=".5"/><circle r="${r}" fill="#ffd16a"/><circle cx="${-r*.25}" cy="-3" r="2.3" fill="#775c31"/><circle cx="${r*.25}" cy="-3" r="2.3" fill="#775c31"/><path d="M-7 7Q0 14 7 7" fill="none" stroke="#775c31" stroke-width="2" stroke-linecap="round"/></g>`;}
function tree(x,y,s=1,color='#89a776'){return `<g transform="translate(${x} ${y}) scale(${s})"><path d="M0 0V-52" stroke="#869275" stroke-width="6"/><path d="M-26-27L0-83L27-27Z" fill="${color}"/><path d="M-23-49L0-100L23-49Z" fill="${color}"/></g>`;}
function robot(x,y,s=1){return `<g transform="translate(${x} ${y}) scale(${s})"><ellipse cy="8" rx="34" ry="8" fill="#233d3220"/><path d="M-13-9L-18 6M13-9L18 6" stroke="#294f46" stroke-width="9" stroke-linecap="round"/><rect x="-23" y="-49" width="46" height="42" rx="14" fill="#fff9df" stroke="#c7d3b2" stroke-width="2"/><path d="M-23-37L-34-24M23-37L37-49" stroke="#294f46" stroke-width="8" stroke-linecap="round"/><path d="M0-60V-72" stroke="#315d4f" stroke-width="4"/><circle cy="-75" r="5" fill="#e9b947"/><rect x="-33" y="-70" width="66" height="41" rx="17" fill="#2e6154"/><rect x="-25" y="-62" width="50" height="25" rx="10" fill="#d2e9c1"/><circle cx="-10" cy="-50" r="4" fill="#294d42"/><circle cx="10" cy="-50" r="4" fill="#294d42"/><path d="M-5-43Q0-39 5-43" stroke="#294d42" stroke-width="2" fill="none"/><circle cy="-20" r="5" fill="#f2c858"/></g>`;}
function skySVG(s){
  const {lat}=CITIES[city],{dec}=SEASONS[season];
  const sx=95+(time-4)/16*770,sy=347-Math.max(-14,s.alt)*3.04;
  let path='';for(let h=4;h<=20.01;h+=.08){const a=altitude(lat,dec,h);if(a>=0)path+=`${path?'L':'M'}${(95+(h-4)/16*770).toFixed(1)},${(347-a*3.04).toFixed(1)} `;}
  const day=s.isDay,high=s.alt>12;
  const top=day?(high?'#cce9ee':'#ecdfd1'):'#233c4c',bottom=day?(high?'#f0f4d9':'#fae4b7'):'#819395';
  const grass=season==='winter'?'#dbe5d9':season==='autumn'?'#cbd499':'#c7dba8';
  return `<svg viewBox="0 0 960 480" role="img" aria-label="${SEASONS[season].name}, 태양 시각 ${clock(time)}, 태양 고도 ${f(s.alt)}도. 시간에 따라 태양 높이를 펼쳐 보여 주는 도식입니다.">
+  <defs><linearGradient id="skyGradient" x2="0" y2="1"><stop stop-color="${top}"/><stop offset="1" stop-color="${bottom}"/></linearGradient><linearGradient id="hillGradient" x2="0" y2="1"><stop stop-color="${grass}"/><stop offset="1" stop-color="#a7c38a"/></linearGradient></defs>
+  <rect width="960" height="480" fill="url(#skyGradient)"/>
+  ${day?`<g fill="#fff" opacity=".55"><path d="M57 153q10-19 25-12q12-24 31-5q20-1 24 17Z"/><path d="M722 117q10-18 25-12q17-28 36-4q20-4 31 16Z"/><path d="M840 233q8-15 22-12q15-21 29-3q23-4 29 15Z"/></g>`:`<g fill="#eaf0d7">${[120,235,330,610,734,855].map((x,i)=>`<circle cx="${x}" cy="${94+i%3*43}" r="2"/>`).join('')}</g>`}
+  <line x1="85" y1="347" x2="875" y2="347" stroke="#708e8644" stroke-dasharray="5 7"/>
+  <line x1="480" y1="85" x2="480" y2="349" stroke="${day?'#74937c66':'#becbb366'}" stroke-dasharray="4 7"/>
+  <path d="${path}" fill="none" stroke="${day?'#94aa8777':'#b3c5ac88'}" stroke-width="3" stroke-dasharray="5 9"/>
+  <text x="480" y="49" text-anchor="middle" fill="${day?'#517161':'#e0ecd8'}" font-size="13">하루 중 가장 높은 곳</text>
+  ${day?`<circle cx="${sx}" cy="${sy}" r="55" fill="#ffecad" opacity=".25"/>${sunFace(sx,sy,30)}`:`<g transform="translate(${sx} ${Math.min(sy,400)})"><circle r="20" fill="#b6c7c0" opacity=".4"/><path d="M-12 0H12" stroke="#d5e1d6" stroke-width="3"/></g>`}
+  <path d="M0 372Q109 323 241 352Q362 293 486 354Q643 280 786 337Q875 308 960 356V480H0Z" fill="${day?'#aec4a0':'#728b80'}"/>
+  <path d="M0 411Q132 353 306 385Q497 345 648 390Q810 334 960 391V480H0Z" fill="url(#hillGradient)"/>
+  <path d="M448 480Q489 419 532 404Q558 391 580 367" fill="none" stroke="#e3e6bc" stroke-width="33" opacity=".8"/>
+  ${tree(105,397,.68)}${tree(145,414,.88,'#71916e')}${tree(842,400,.6)}${tree(882,422,.83,'#739a75')}
+  <g transform="translate(670 365)"><ellipse cx="0" cy="39" rx="84" ry="13" fill="#76906a20"/><path d="M-48-8V37H48V-8" fill="#f1efd7" stroke="#abb69c" stroke-width="2"/><path d="M-59-9A59 59 0 0 1 59-9Z" fill="#8dafa4"/><path d="M-11-66Q14-45 11-9" fill="none" stroke="#c3d5c0" stroke-width="8"/><path d="M-19 36V8Q0-9 19 8V36" fill="#335f52"/><rect x="-42" y="8" width="15" height="14" rx="3" fill="#b7d7d0"/><rect x="27" y="8" width="15" height="14" rx="3" fill="#b7d7d0"/><path d="M30-52L68-84" stroke="#416b60" stroke-width="17"/><path d="M63-91L75-77" stroke="#e7e9ca" stroke-width="5" stroke-linecap="round"/></g>
+  ${robot(381,409,1.08)}
+  <g fill="${day?'#526e54':'#263e32'}" font-size="13"><text x="59" y="456">아침</text><text x="480" y="456" text-anchor="middle">남중</text><text x="901" y="456" text-anchor="end">저녁</text></g>
+  <g fill="#8ba477" opacity=".65"><path d="M250 430l4-7m0 8l6-5M730 445l3-8m0 9l6-5M199 450l3-8m0 9l6-5" stroke="#809e69" stroke-width="2"/></g>
+  </svg>`.replaceAll('\n+','\n');
}
function angleSVG(alt,shadow,options={}){
  const {hideNumber=false,mini=false,poleHeight=1}=options;
  const a=Math.max(0,Math.min(90,alt)),r=a*Math.PI/180,bx=mini?65:125,by=mini?136:207,R=mini?76:143;
  const sx=bx+R*Math.cos(r),sy=by-R*Math.sin(r),px=mini?268:520,ph=mini?33:57*poleHeight;
  const maxWidth=mini?98:179,shadowPx=shadow===null?0:Math.min(maxWidth,shadow*(mini?33:57)),end=px-shadowPx;
  const W=mini?310:600,H=mini?180:290;
  const arcR=mini?28:48,ax=bx+arcR*Math.cos(r),ay=by-arcR*Math.sin(r);
  return `<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="${hideNumber?'각도를 추리하는':'태양 고도와 그림자의'} 옆모습 그림${hideNumber?'':`, 태양 고도 ${f(alt)}도`}">
+  <rect width="${W}" height="${H}" fill="#f6f8f1"/>
+  <path d="M${bx} ${by} L${bx+R+10} ${by}" stroke="#9bab8d" stroke-width="2"/>
+  <path d="M${bx} ${by} L${sx} ${sy}" stroke="#dbb349" stroke-width="2" stroke-dasharray="4 4"/>
+  ${alt>0?`<path d="M${bx} ${by}L${bx+arcR} ${by}A${arcR} ${arcR} 0 0 0 ${ax} ${ay}Z" fill="#f3d78455" stroke="#ba8f2b" stroke-width="1.5"/>${sunFace(sx,sy,mini?10:18)}`:`<text x="${bx}" y="${by-50}" fill="#6d7d6c" font-size="15">태양은 지평선 아래</text>`}
+  <circle cx="${bx}" cy="${by}" r="4" fill="#315a49"/>
+  <text x="${bx-5}" y="${by+23}" text-anchor="middle" fill="#5e755b" font-size="${mini?9:12}">관찰 지점</text>
+  ${!mini?`<text x="${bx+R-10}" y="${by+23}" text-anchor="middle" fill="#5e755b" font-size="12">지평선</text>`:''}
+  <text x="${bx+67}" y="${by-13}" fill="#8b691e" font-size="${mini?13:20}" font-weight="700">${alt<=0?'—':hideNumber?'?°':`${f(alt)}°`}</text>
+  <path d="M${px-maxWidth-10} ${by}H${W-22}" stroke="#a9bda0" stroke-width="2"/>
+  <path d="M${px} ${by}H${end}" stroke="#6b8670" stroke-width="${mini?6:10}" stroke-linecap="round"/>
+  <path d="M${px} ${by}V${by-ph}" stroke="#ca9773" stroke-width="${mini?6:9}" stroke-linecap="round"/>
+  ${alt>0?`<path d="M${px+ph/Math.tan(r)} ${by-ph*2} L${px} ${by-ph} L${end} ${by}" fill="none" stroke="#dfb557" stroke-width="2" stroke-dasharray="5 4"/>`:''}
+  <text x="${px}" y="${by-ph-12}" text-anchor="middle" fill="#6e7c64" font-size="${mini?9:12}">막대</text>
+  <text x="${px-43}" y="${by+24}" text-anchor="middle" fill="#53694e" font-size="${mini?9:12}">${shadow===null?'직사광 그림자 없음':shadowPx>=maxWidth?'← 긴 그림자':'그림자'}</text>
+  ${!mini?`<text x="300" y="273" text-anchor="middle" fill="#819177" font-size="11">태양과 막대를 옆에서 본 그림 · 두 그림의 햇빛은 같은 각도로 내려와요</text>`:''}
+  </svg>`.replaceAll('\n+','\n');
}
function seasonButtons(){return Object.entries(SEASONS).map(([key,s])=>`<button class="season-btn ${season===key?'selected':''}" style="--season-color:${s.color}" data-season="${key}" aria-pressed="${season===key}"><span aria-hidden="true">${s.icon}</span>${s.name}</button>`).join('');}
function description(s){if(!s.isDay)return ['아직 태양이 지평선 아래에 있어.','슬라이더를 낮으로 옮기면 태양과 그림자를 관찰할 수 있어.'];if(s.isNoon)return ['바로 여기! 하루 중 태양이 가장 높아.','우리나라에서 이때를 남중, 이때의 각도를 남중고도라고 해.'];return [time<12?'태양이 올라가면, 그림자는 짧아져.':'태양이 내려가면, 그림자는 길어져.',`지금은 태양 고도 ${f(s.alt)}°. ‘남중으로’를 눌러 가장 높은 때와 비교해 봐.`];}
function renderLab(){
  $('#screen').innerHTML=`<div class="intro"><div><div class="eyebrow">EXPERIMENT 01 · 태양과 그림자</div><h1>태양을 움직여 봐.<br>그림자가 답을 알려줄 거야.</h1><p>슬라이더로 하루를 여행하며, 태양이 가장 높아지는 순간을 찾아봐.</p></div><span class="intro-badge">✦ 초등 과학 · 남중고도</span></div>
+  <div class="lab-grid"><section class="scene-card" aria-label="태양 관찰 화면"><div class="scene-top"><span class="scene-tag" id="scene-label"></span><span class="scene-tag dark" id="sky-state"></span></div><div class="sky-wrap" id="sky"></div><div class="scene-bottom"><div class="mascot-mini" aria-hidden="true">☀</div><div><b id="explain-title"></b><p id="explain-body"></p></div></div></section>
+  <section class="panel controls" aria-label="실험 조절판"><div class="control-head"><h2>나의 실험 조절판</h2><span>CONTROL ROOM</span></div><div class="city-row"><label for="city">관찰하는 곳</label><select id="city">${Object.entries(CITIES).map(([k,c])=>`<option value="${k}" ${city===k?'selected':''}>${c.name} · 북위 ${c.lat.toFixed(1)}°</option>`).join('')}</select></div><div><div class="label-row">계절을 골라 봐 <span class="fine" style="padding:0;background:none" id="term"></span></div><div class="season-buttons" id="season-buttons">${seasonButtons()}</div></div>
+  <div><div class="label-row"><label for="time">태양 시각</label><button class="text-btn" data-action="time-help">이 시각은?</button></div><div class="clock" id="time-label"></div><input type="range" id="time" min="4" max="20" step="0.1" value="${time}" aria-label="태양 시각 조절"><div class="range-labels"><span>04:00</span><span>12:00 남중</span><span>20:00</span></div><div class="time-presets"><button data-time="8">오전 8시</button><button data-time="12">남중으로 ☀</button><button data-time="16">오후 4시</button></div></div>
+  <div class="actions"><button class="secondary" data-action="play" id="play">▷ 하루 재생</button><button class="secondary" data-action="capture">＋ 관찰 저장</button></div><p class="fine">12:00을 남중으로 정한 <b>학습용 태양 시각</b>이야. 실제 시계의 12시와는 다를 수 있어.</p></section></div>
+  <div class="metrics"><div class="metric"><div><span class="metric-label">지금 태양 고도</span><strong id="alt-metric"></strong></div><span class="metric-symbol">∠</span></div><div class="metric"><div><span class="metric-label" id="shadow-label"></span><strong id="shadow-metric"></strong></div><span class="metric-symbol">↘</span></div><div class="metric"><div><span class="metric-label">이 계절의 남중고도</span><strong id="noon-metric"></strong></div><span class="metric-symbol">☀</span></div></div>
+  <div class="two-col"><section class="panel"><div class="section-head"><h2>고도는 ‘올려다보는 각도’</h2><label class="switch-label"><input id="show-angle" type="checkbox" ${showAngle?'checked':''}> 각도 보기</label></div><div class="diagram" id="angle-diagram"></div><div class="city-row" style="margin-top:12px"><label for="height">막대 높이 바꾸기</label><select id="height">${[.5,1,1.5,2].map(h=>`<option value="${h}" ${h===height?'selected':''}>${h}m</option>`).join('')}</select></div><p class="diagram-explain"><b>지평선과 태양을 향한 선 사이의 각도</b>가 태양 고도야. 태양을 더 높이 올려다볼수록 각도가 커져.</p><button class="text-btn" data-action="listen-lab">♫ 설명 읽어 주기</button></section>
+  <section class="panel"><div class="section-head"><h2>오늘의 발견 미션</h2><span class="mini-label" id="mission-count"></span></div><div class="mission-list" id="mission-list"></div><p class="mission-feedback" id="mission-message"></p><button class="primary wide" data-action="check-mission">지금 관찰로 미션 확인하기 ✓</button></section></div>
+  <div class="tip-banner"><span aria-hidden="true">⌁</span><p>화면의 하늘은 <b>시간에 따른 태양 높이를 펼쳐 본 도식</b>이야. 실제 방향은 남중 때 태양이 남쪽, 그림자는 북쪽! 야외에서는 태양을 직접 보지 말고 막대 그림자로 관찰해.</p></div>`.replaceAll('\n+','\n');
  updateLab();updateMissions();
}
function updateLab(){
  if(tab!=='lab')return;const s=sunState(city,season,time,height),[head,body]=description(s);
  $('#sky').innerHTML=skySVG(s);$('#scene-label').innerHTML=`<b>${CITIES[city].name}의 하늘</b>${SEASONS[season].term} · 펼쳐 본 도식`;$('#sky-state').textContent=s.isNoon?'☀ 남중! 가장 높은 순간':s.isDay?'● 관찰 중':'☾ 지평선 아래';
  $('#explain-title').textContent=head;$('#explain-body').textContent=body;$('#term').textContent=SEASONS[season].term;$('#time-label').innerHTML=`${clock(time)}<small>${s.isNoon?'남중':time<12?'오전':'오후'}</small>`;$('#time').value=time;$('#time').setAttribute('aria-valuetext',`태양 시각 ${clock(time)}`);
  $('#alt-metric').innerHTML=s.isDay?`${f(s.alt)}°<small>지평선에서 올려다본 각도</small>`:`지평선 아래<small>태양 고도 ${f(s.alt)}°</small>`;
  $('#shadow-label').textContent=`${height}m 막대의 그림자`;
  $('#shadow-metric').innerHTML=`${shadowText(s.shadow)}<small>${s.isNoon?'하루 중 가장 짧아!':s.isDay?'같은 막대로 비교해 봐':'직접 햇빛이 닿지 않아요'}</small>`;
  $('#noon-metric').innerHTML=`${f(s.noon)}°<small>오늘 모형의 가장 큰 각도</small>`;
  $('#angle-diagram').innerHTML=angleSVG(s.alt,s.shadow,{hideNumber:!showAngle,poleHeight:height});
  $('#play').textContent=playing?'Ⅱ 잠깐 멈추기':'▷ 하루 재생';$('#play').setAttribute('aria-pressed',String(playing));
  $$('.season-btn').forEach(b=>{const active=b.dataset.season===season;b.classList.toggle('selected',active);b.setAttribute('aria-pressed',String(active));});
}
function updateMissions(){
  if(!$('#mission-list'))return;$('#mission-count').textContent=`${progress.missions.length} / 4 발견`;
  $('#mission-list').innerHTML=MISSIONS.map((m,i)=>`<button class="mission-item ${progress.missions.includes(m.id)?'done':''} ${i===activeMission?'current':''}" data-mission="${i}" aria-pressed="${i===activeMission}"><span class="number">${progress.missions.includes(m.id)?'✓':i+1}</span><span><b>${m.title}</b><small>${i===activeMission?m.text:progress.missions.includes(m.id)?'발견 완료 · 다시 해도 좋아':'눌러서 미션 선택하기'}</small></span><span>${i===activeMission?'●':'↗'}</span></button>`).join('');
  $('#mission-message').textContent=lastMissionMessage||MISSIONS[activeMission].hint;
}
function checkMission(){pause();const m=MISSIONS[activeMission],s={...sunState(city,season,time,height),season,time};if(m.check(s)){if(!progress.missions.includes(m.id)){progress.missions.push(m.id);save();confetti();}lastMissionMessage=m.done;chime('win');toast(`미션 성공! ${m.title}`);}else{lastMissionMessage=`다시 관찰해 보자. ${m.hint}`;chime('retry');}updateMissions();}
function capture(){pause();const id=[city,season,time,height].join(':');if(progress.notes.some(n=>n.id===id)){toast('같은 관찰이 이미 연구 노트에 있어. 다른 시간이나 계절을 저장해 봐.');return;}progress.notes.push({id,city,season,time,height});if(progress.notes.length>20)progress.notes.shift();save();chime();toast('연구 노트에 저장했어! 계절과 시간을 바꿔 비교해 봐.');}
function pause(){playing=false;cancelAnimationFrame(raf);lastFrame=0;if($('#play')){$('#play').textContent='▷ 하루 재생';$('#play').setAttribute('aria-pressed','false');}}
function togglePlay(){if(playing){pause();return;}if(time>=20)time=4;playing=true;lastFrame=0;function frame(now){if(!playing)return;if(lastFrame){time=Math.min(20,time+(now-lastFrame)/1500);if(time>=20)pause();}lastFrame=now;updateLab();if(playing)raf=requestAnimationFrame(frame);}raf=requestAnimationFrame(frame);updateLab();}
function renderSeasons(){
  $('#screen').innerHTML=`<div class="intro tab-intro"><div><div class="eyebrow">EXPERIMENT 02 · 계절과 햇빛</div><h1>똑같은 점심 무렵인데,<br>왜 태양 높이는 다를까?</h1><p>같은 장소, 같은 1m 막대, 같은 남중 때를 비교해 봐.</p></div><select id="city" aria-label="계절을 비교할 지역">${Object.entries(CITIES).map(([k,c])=>`<option value="${k}" ${city===k?'selected':''}>${c.name} 기준</option>`).join('')}</select></div>
+  <div class="season-grid">${Object.entries(SEASONS).map(([k,s])=>{const a=noonAltitude(CITIES[city].lat,s.dec),sh=shadowLength(a);return `<article class="season-card ${k===season?'active':''}" style="--season-color:${s.color}"><div class="season-card-top"><div><h3>${s.name}</h3><small>${s.term}</small></div><span class="season-mark">${s.icon}</span></div>${angleSVG(a,sh,{mini:true})}<div class="season-card-info"><strong>${f(a)}°</strong><p>${s.detail}</p><div class="season-data"><span>남중 그림자 <b>${shadowText(sh)}</b></span><span>낮의 길이 <b>${duration(daylight(CITIES[city].lat,s.dec))}</b></span></div><button class="secondary wide" data-explore-season="${k}">실험실에서 관찰하기 ↗</button></div></article>`;}).join('')}</div>
+  <div class="tip-banner"><span>∠</span><p><b>남중고도: 여름(하지) &gt; 봄·가을(춘분·추분) &gt; 겨울(동지).</b> 남중 그림자 길이는 반대야. 이 관계는 우리나라를 기준으로 해.</p></div>
+  <section class="panel" style="margin-top:22px"><div class="eyebrow">LIGHT EXPERIMENT</div><div class="section-head"><h2>같은 햇빛, 좁게 모일까? 넓게 퍼질까?</h2></div><div class="energy-layout"><div class="diagram" id="energy-diagram"></div><div class="energy-copy"><p>같은 양의 햇빛을 땅에 비춰 보자. 태양 고도가 높을수록 좁은 땅에 모여서, 같은 넓이의 땅이 더 많은 에너지를 받아.</p><div class="label-row"><label for="energy">태양 고도</label><strong id="energy-value"></strong></div><input id="energy" type="range" min="15" max="85" step="1" value="${energyAngle}"><div class="range-labels"><span>15° 낮게</span><span>85° 높게</span></div><div class="energy-bar"><span id="energy-fill"></span></div><div class="big-stat" id="energy-stat"></div><small class="fine">90°일 때를 100%로 본 같은 넓이의 땅이 받는 에너지. 구름·대기는 빼고 각도만 비교한 모형이야.</small></div></div></section>
+  <section class="panel earth-panel"><div class="earth-content"><div><div class="eyebrow">ONE MORE DISCOVERY</div><h2>계절의 비밀은<br>기울어진 지구에 있어.</h2><p>지구는 자전축이 약 23.4° 기울어진 채, 거의 같은 방향을 유지하며 태양 주위를 돌아. 우리나라가 있는 북반구가 태양 쪽으로 기울 때 남중고도가 높아지고 낮도 길어져.</p><div class="pill-row"><button class="pill ${tilt?'active':''}" data-tilt="yes" aria-pressed="${tilt}">기울기 23.4°</button><button class="pill ${!tilt?'active':''}" data-tilt="no" aria-pressed="${!tilt}">기울기 0°라면?</button></div><p id="tilt-message"></p></div><div><div id="earth-diagram"></div><div class="earth-caption">북반구 기준 · 크기와 거리를 줄인 개념도<br>자전축 기울기는 공전 궤도면에 수직인 방향과 비교해.</div></div></div></section>`.replaceAll('\n+','\n');
  updateEnergy();updateEarth();
}
function updateEnergy(){
  const rad=energyAngle*Math.PI/180,rel=Math.sin(rad),span=75/rel,x1=195-span/2,x2=195+span/2,dx=125/Math.tan(rad);
  $('#energy-diagram').innerHTML=`<svg viewBox="0 0 420 270" role="img" aria-label="태양 고도 ${energyAngle}도, 같은 넓이의 땅이 받는 에너지 ${Math.round(rel*100)}퍼센트"><defs><pattern id="soilGrid" width="25" height="20" patternUnits="userSpaceOnUse"><path d="M25 0H0V20" fill="none" stroke="#bfcbb233"/></pattern></defs><rect width="420" height="270" fill="#f5f7ed"/><path d="M${x1-dx} 64 L${x2-dx} 64 L${x2} 189 L${x1} 189Z" fill="#f5ce6377"/><path d="M${x1-dx} 64L${x1} 189M${x2-dx} 64L${x2} 189" stroke="#d6aa3f" stroke-width="2"/><path d="M195 199H${x1}" stroke="#d8b253" stroke-width="5"/><path d="M195 199H${x2}" stroke="#d8b253" stroke-width="5"/><rect y="202" width="420" height="68" fill="#d8e4c0"/><rect y="202" width="420" height="68" fill="url(#soilGrid)"/><text x="210" y="35" fill="#547057" font-size="13" text-anchor="middle">같은 양의 햇빛 ↓</text><text x="210" y="245" text-anchor="middle" font-size="14" fill="#416347">${energyAngle<45?'넓은 땅에 나누어 받아요':'좁은 땅에 모여 받아요'}</text></svg>`;
  $('#energy-value').textContent=`${energyAngle}°`;$('#energy-fill').style.width=`${rel*100}%`;$('#energy-stat').innerHTML=`${Math.round(rel*100)}% <small>의 에너지를 받아요</small>`;
}
function earthAt(x,side){const angle=tilt?23.4:0;return `<g transform="translate(${x} 136)"><circle r="55" fill="#679f9a"/><path d="M-30-34Q-12-50 2-36L17-37L31-17L9-5L2 18L-12 25L-23 3L-38-5Z" fill="#b4cd7e"/><path d="M10 28L29 13L43 22L35 40L17 49Z" fill="#b4cd7e"/><path d="${side==='left'?'M0-55A55 55 0 0 0 0 55Z':'M0-55A55 55 0 0 1 0 55Z'}" fill="#102e3955"/><g transform="rotate(${angle})"><line x1="0" x2="0" y1="-80" y2="80" stroke="#f1ecca" stroke-width="3"/><text y="-87" text-anchor="middle" fill="#e4f0d4" font-size="14">N</text><line x1="-50" x2="50" y1="0" y2="0" stroke="#e8efcd88" stroke-width="1.5" stroke-dasharray="4 4"/></g><text y="111" text-anchor="middle" fill="#e5edd5" font-size="14">${side==='left'?'6월 · 북반구':'12월 · 북반구'}</text><text y="132" text-anchor="middle" fill="#edcf75" font-size="13">${tilt?(side==='left'?'태양 쪽으로 기울어요':'태양 반대쪽으로 기울어요'):'계절별 남중고도 변화 없음'}</text></g>`;}
function updateEarth(){
  $('#earth-diagram').innerHTML=`<svg viewBox="0 0 540 300" role="img" aria-label="${tilt?'같은 방향으로 기울어진 지구 자전축. 북반구는 6월에 태양 쪽, 12월에 반대쪽으로 기웁니다.':'기울기가 없다면 두 위치의 태양 남중고도가 같습니다.'}">${earthAt(95,'left')}${earthAt(445,'right')}<g stroke="#e8c97677" stroke-width="2"><path d="M211 121H165M211 146H165M329 121H375M329 146H375"/><path d="M174 117L165 121L174 125M174 142L165 146L174 150M366 117L375 121L366 125M366 142L375 146L366 150" fill="none"/></g>${sunFace(270,134,31)}</svg>`;
  $('#tilt-message').textContent=tilt?'태양과 가까워져서 여름이 되는 게 아니야. 태양을 향한 기울기와 낮의 길이가 핵심!':'기울기가 0°라면 같은 지역의 남중고도와 낮의 길이가 계절에 따라 거의 변하지 않아. 지금과 같은 뚜렷한 계절 변화도 생기기 어려워.';
  $$('[data-tilt]').forEach(b=>{const active=(b.dataset.tilt==='yes')===tilt;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active));});
}
function renderGame(){
  if(game.done){$('#screen').innerHTML=`<div class="quiz-shell panel result"><div class="result-medal">⚑</div><div class="eyebrow" style="justify-content:center">ANGLE EXPLORER</div><h2>각도 탐정, 임무 완료!</h2><p>5문제 중 ${game.stars}문제를 오차 5° 이내로 맞혔어.<br>최고 기록은 ${progress.gameBest} / 5. 그림을 보고 각도를 어림하는 힘이 자라고 있어.</p><div class="actions"><button class="primary" data-action="game-reset">다른 순서로 다시 도전</button><button class="secondary" data-go="quiz">확인 퀴즈로 →</button></div></div>`;return;}
  const target=game.targets[game.round],sh=shadowLength(target),error=Math.abs(game.guess-target),good=error<=5;
  $('#screen').innerHTML=`<div class="intro tab-intro"><div><div class="eyebrow">CHALLENGE · 각도 탐정</div><h1>숨어 있는 태양 각도를 찾아라!</h1><p>왼쪽 그림의 태양을 올려다봐. 몇 도쯤일까? 오차 5° 이내면 별을 얻어.</p></div><span class="intro-badge">최고 기록 ${progress.gameBest} / 5 ★</span></div><div class="rounds">${game.targets.map((_,i)=>`<span class="round-dot ${i===game.round?'current':i<game.round?'passed':''}">${i<game.round?'✓':i+1}</span>`).join('')}</div><div class="game-layout"><section class="panel"><div class="section-head"><h2>비밀 관찰 카드 ${game.round+1}</h2><span class="mini-label">1m 막대</span></div><div class="game-stage">${angleSVG(target,sh,{hideNumber:!game.submitted})}</div><div class="game-guide">그림자 길이는 <b>${shadowText(sh)}</b>야. ${game.submitted?'각도와 그림자 길이의 관계를 다시 살펴봐.':'그림자가 짧으면 태양은 높고, 길면 태양은 낮아.'}</div></section><section class="panel game-controls"><div class="eyebrow">MY GUESS</div><h2>내가 생각한 각도는…</h2><div class="big-stat" id="guess-number">${game.guess}°</div><div class="stepper"><button data-step="-1" aria-label="각도 1도 줄이기" ${game.submitted?'disabled':''}>−</button><input type="range" id="guess" min="5" max="85" step="1" value="${game.guess}" aria-label="예상 태양 고도" ${game.submitted?'disabled':''}><button data-step="1" aria-label="각도 1도 늘리기" ${game.submitted?'disabled':''}>＋</button></div>${game.submitted?`<div class="feedback ${good?'':'error'}" role="status"><b>${good?'★ 별을 얻었어!':'아하! 이 각도였구나.'}</b>정답은 ${target}°. 내 예상 ${game.guess}°와 ${error}° 차이야. ${target>=60?'태양이 높으니 그림자가 아주 짧지?':target<=30?'태양이 낮으니 그림자가 길게 늘어났지?':'45°일 때는 1m 막대와 그림자 길이가 같아. 비교 기준으로 기억해 봐.'}</div><button class="primary wide" data-action="game-next">${game.round===4?'탐정 결과 보기':'다음 관찰 카드 →'}</button>`:`<button class="primary yellow wide" data-action="game-submit">이 각도로 정답 확인! ✓</button><p class="fine" style="margin-top:17px">계산할 필요 없어. 지평선은 0°, 머리 위는 90°. 그 절반인 45°를 기준으로 어림해 봐.</p>`}</section></div>`;
}
function submitGame(){if(game.submitted||game.done)return;game.submitted=true;if(Math.abs(game.guess-game.targets[game.round])<=5){game.stars++;chime();}else chime('retry');renderGame();}
function nextGame(){if(!game.submitted)return;if(game.round===4){game.done=true;progress.gameBest=Math.max(progress.gameBest,game.stars);save();chime('win');confetti();}else{game.round++;game.guess=45;game.submitted=false;}renderGame();}
function startQuiz(wrongOnly=false){const ids=wrongOnly?QUIZ.filter(q=>progress.wrong.includes(q.id)).map(q=>q.id):QUIZ.map(q=>q.id);if(!ids.length){toast('복습할 오답이 없어. 전체 퀴즈에 도전해 봐!');return;}quizSession={ids,index:0,answer:null,correct:0,finished:false,wrongOnly};renderQuiz();}
function renderQuiz(){
  const intro=`<div class="tab-intro"><div class="eyebrow">CHECK YOUR DISCOVERY</div><h1>발견한 것을 내 지식으로.</h1><p>틀려도 괜찮아. 이유를 읽는 순간, 새로운 발견이 시작돼.</p></div>`;
  if(!quizSession){$('#screen').innerHTML=`${intro}<div class="quiz-shell panel quiz-welcome"><div class="quiz-illustration"><svg viewBox="0 0 260 255" aria-hidden="true"><circle cx="130" cy="128" r="107" fill="#e0e9ce"/>${sunFace(180,61,27)}${robot(103,201,1.6)}<path d="M163 203l18 12 28-38" fill="none" stroke="#64896b" stroke-width="9" stroke-linecap="round" stroke-linejoin="round"/></svg></div><div><span class="mini-label">12문제 · 시간 제한 없음</span><h2 style="margin-top:15px">남중고도,<br>얼마나 이해했을까?</h2><p>각도, 그림자, 계절의 연결고리를 확인해 봐. 답을 고르면 바로 이유를 알려 줄게.</p><div class="actions"><button class="primary" data-action="quiz-start">퀴즈 시작하기 →</button>${progress.wrong.length?`<button class="secondary" data-action="quiz-review">오답 ${progress.wrong.length}개 복습</button>`:''}</div><p class="fine">지금까지 이해한 문제 ${progress.mastered.length} / 12</p></div></div>`;return;}
  const qs=quizSession;
  if(qs.finished){$('#screen').innerHTML=`${intro}<div class="quiz-shell panel result"><div class="result-medal">${qs.correct===qs.ids.length?'★':'☀'}</div><h2>${qs.correct===qs.ids.length?'모두 발견했어!':'배운 만큼 더 선명해진 태양!'}</h2><p>${qs.ids.length}문제 중 ${qs.correct}문제를 맞혔어.<br>${progress.wrong.length?`헷갈렸던 ${progress.wrong.length}문제만 한 번 더 풀어 보면 더 오래 기억할 수 있어.`:'태양 고도가 커지면 그림자는 짧아져. 이 연결을 기억하자!'}</p><div class="actions">${progress.wrong.length?'<button class="primary" data-action="quiz-review">오답만 다시 풀기</button>':''}<button class="secondary" data-action="quiz-start">전체 다시 풀기</button><button class="secondary" data-go="notes">연구 노트 보기 →</button></div></div>`;return;}
  const q=QUIZ.find(q=>q.id===qs.ids[qs.index]),answered=qs.answer!==null,ok=qs.answer===q.answer;
  $('#screen').innerHTML=`${intro}<div class="quiz-shell panel"><div class="quiz-progress"><span>${qs.wrongOnly?'오답 복습':'확인 퀴즈'} ${qs.index+1} / ${qs.ids.length}</span><div class="progress-bar"><i style="width:${(qs.index+(answered?1:0))/qs.ids.length*100}%"></i></div><span>${qs.correct}개 정답</span></div><h2 class="quiz-question">${q.q}</h2><div class="answers">${q.choices.map((choice,i)=>`<button class="answer ${answered?(i===q.answer?'correct':i===qs.answer?'wrong':''):''}" data-answer="${i}" ${answered?'disabled':''}><span>${answered&&i===q.answer?'✓':i+1}</span>${choice}</button>`).join('')}</div>${answered?`<div class="feedback ${ok?'':'error'}" role="status"><b>${ok?'정확해! 이렇게 기억하자.':'괜찮아. 여기서 배워 보자.'}</b>${q.why}<br><button class="text-btn" data-action="listen-quiz">♫ 풀이 읽어 주기</button></div><button class="primary wide" data-action="quiz-next">${qs.index===qs.ids.length-1?'내 결과 보기':'다음 문제 →'}</button>`:`<p class="fine" style="margin-top:19px">답을 고르면 바로 풀이를 볼 수 있어. 서두르지 않아도 돼.</p>`}</div>`;
}
function answerQuiz(answer){const qs=quizSession;if(!qs||qs.answer!==null||qs.finished)return;const q=QUIZ.find(q=>q.id===qs.ids[qs.index]);qs.answer=answer;if(answer===q.answer){qs.correct++;if(!progress.mastered.includes(q.id))progress.mastered.push(q.id);progress.wrong=progress.wrong.filter(id=>id!==q.id);chime();}else{if(!progress.wrong.includes(q.id))progress.wrong.push(q.id);progress.mastered=progress.mastered.filter(id=>id!==q.id);chime('retry');}save();renderQuiz();}
function nextQuiz(){if(!quizSession||quizSession.answer===null)return;if(quizSession.index===quizSession.ids.length-1){quizSession.finished=true;chime('win');confetti();}else{quizSession.index++;quizSession.answer=null;}window.speechSynthesis?.cancel();renderQuiz();$('#screen').focus({preventScroll:true});}
function renderNotes(){
  const badges=[...MISSIONS.map(m=>({name:m.title,icon:m.icon,earned:progress.missions.includes(m.id),desc:'발견 미션'})),{name:'각도 탐정',icon:'⚑',earned:progress.gameBest>=4,desc:'게임 4개 이상 정답'},{name:'태양 박사',icon:'★',earned:progress.mastered.length===12,desc:'12문제 모두 이해'}];
  const rows=[...progress.notes].reverse().map(n=>{const s=sunState(n.city,n.season,n.time,n.height);return `<tr><td>${CITIES[n.city].name}</td><td>${SEASONS[n.season].name}</td><td>${clock(n.time)}${s.isNoon?' ☀':''}</td><td>${n.height}m</td><td>${f(s.alt)}°</td><td>${shadowText(s.shadow)}</td><td><button data-delete-note="${escape(n.id)}" aria-label="${SEASONS[n.season].name} ${clock(n.time)} 관찰 삭제">삭제</button></td></tr>`;}).join('');
  $('#screen').innerHTML=`<div class="tab-intro"><div class="eyebrow">MY RESEARCH NOTE</div><h1>하준이의 작은 발견들.</h1><p>직접 관찰한 기록과 배지를 한곳에 모았어. 다시 볼수록 오래 기억돼.</p></div><div class="notes-top"><section class="panel"><div class="section-head"><h2>나의 연구원 배지</h2><span class="mini-label">${badges.filter(b=>b.earned).length} / 6 수집</span></div><div class="badge-grid">${badges.map(b=>`<div class="badge ${b.earned?'earned':''}"><div class="badge-icon">${b.earned?b.icon:'◇'}</div><b>${b.name}</b><small>${b.earned?'획득 완료!':b.desc}</small></div>`).join('')}</div></section><section class="panel"><div class="section-head"><h2>이 세 문장은 꼭 기억해.</h2><button class="text-btn" data-action="listen-summary">♫ 듣기</button></div><div class="summary-note"><span>01</span><div><b>고도는 ‘거리’가 아니라 ‘각도’.</b><p>지평선에서 태양을 얼마나 올려다보는지 나타내.</p></div></div><div class="summary-note"><span>02</span><div><b>남중 때 가장 높고, 그림자는 가장 짧아.</b><p>하루 동안 같은 장소, 같은 막대로 비교한 결과야.</p></div></div><div class="summary-note"><span>03</span><div><b>여름엔 높게, 겨울엔 낮게.</b><p>우리나라의 하지·동지 무렵을 비교한 남중고도야. 계절마다 낮의 길이도 달라져.</p></div></div></section></div><section class="panel" style="margin-top:22px"><div class="section-head"><h2>내가 저장한 관찰</h2><button class="secondary" data-go="lab">＋ 관찰하러 가기</button></div><p class="fine">최근 20개 관찰 · 같은 장소와 같은 막대 높이끼리 비교해 봐.</p>${rows?`<div class="table-wrap"><table class="notebook-table"><caption class="fine" style="text-align:left;padding:10px">시각은 학습용 태양 시각이며 ☀는 남중을 뜻해.</caption><thead><tr><th>지역</th><th>계절</th><th>태양 시각</th><th>막대</th><th>태양 고도</th><th>그림자</th><th>관리</th></tr></thead><tbody>${rows}</tbody></table></div>`:'<div class="empty">아직 관찰 기록이 없어.<br>실험실에서 ‘관찰 저장’을 누르면 여기에 모여.</div>'}<div class="note-compare">비교해 볼까? 여름과 겨울을 각각 남중으로 맞추고 저장해 봐. 어느 계절의 태양은 높고 그림자는 짧을까?</div></section><div class="tip-banner"><span>✓</span><p>태양 고도가 높다고 그 순간 기온이 반드시 가장 높은 것은 아니야. 땅과 공기가 데워지는 데는 시간이 걸려.</p></div><button class="danger-text" data-action="reset-confirm" style="margin-top:15px">이 브라우저의 학습 기록 초기화</button>`;
}
function navigate(next,focus=false){
  if(!['lab','seasons','game','quiz','notes'].includes(next))next='lab';pause();window.speechSynthesis?.cancel();tab=next;history.replaceState(null,'',`#${tab}`);$$('[data-tab]').forEach(b=>{const active=b.dataset.tab===tab;b.classList.toggle('active',active);if(active)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});
  ({lab:renderLab,seasons:renderSeasons,game:renderGame,quiz:renderQuiz,notes:renderNotes})[tab]();if(focus){$('#screen').focus({preventScroll:true});window.scrollTo({top:Math.max(0,$('.tabs').offsetTop-12),behavior:'smooth'});}
}
function timeHelp(){modal('태양 시각 12:00이란?',`<p>이 앱은 태양이 남중하는 순간을 12:00으로 정했어. 시간을 바꿀 때 태양 높이가 어떻게 달라지는지 쉽게 비교하기 위한 <b>태양 시각</b>이야.</p><div class="source-note"><p>우리가 보는 시계는 한국 표준시를 써. 실제 남중 시각은 지역의 동서 위치와 날짜에 따라 달라지므로, 시계로 정확히 낮 12시가 아닐 수 있어.</p></div><p>실제 관측을 한다면 한국천문연구원의 일출일몰 계산에서 지역과 날짜에 맞는 남중 시각을 확인해.</p>`);}
function help(){modal('하준 연구원, 연구소에 온 걸 환영해!',`<p>공식부터 외울 필요 없어. 움직이고, 발견하고, 퀴즈로 확인해 보자.</p><div class="help-steps"><div class="help-step"><span>1</span><div><b>태양을 움직여 봐</b>실험실에서 시간 슬라이더를 움직여. ‘남중으로’를 누르면 가장 높은 순간이야.</div></div><div class="help-step"><span>2</span><div><b>계절을 바꿔 비교해</b>여름과 겨울의 남중고도, 그림자 길이를 비교하고 관찰 저장을 눌러 봐.</div></div><div class="help-step"><span>3</span><div><b>게임하고 내 말로 설명해</b>각도 탐정과 퀴즈에 도전해. 틀린 문제는 풀이를 듣고 다시 풀 수 있어.</div></div></div><p>야외에서는 태양을 직접 쳐다보지 말고 막대 그림자로 관찰해. 설명 듣기는 기기의 한국어 음성을 사용해.</p>`);}
function sources(){modal('학습 기준 · 참고 자료',`<div class="sources"><p>우리나라 초등 과학 ‘계절의 변화’의 핵심 관계를 익히기 위한 학습 모형이야.</p><div class="source-note"><p>춘분·추분의 태양 적위 0°, 하지 +23.4°, 동지 −23.4°를 사용해. 지역 위도와 태양 시각으로 고도를 계산하고, 같은 수직 막대의 그림자를 비교해.</p><p>계절 전체의 평균이 아니라 각 절기 무렵을 대표해. 낮의 길이는 태양 중심이 지평선 위에 있는 시간이며, 대기 굴절·산·건물·태양 크기는 반영하지 않았어. 실제 관측값과 조금 다를 수 있어.</p></div><a href="https://astro.kasi.re.kr/life/pageView/10" target="_blank" rel="noopener noreferrer">한국천문연구원 · 태양 고도와 방위각 ↗</a><a href="https://gml.noaa.gov/grad/solcalc/solareqns.PDF" target="_blank" rel="noopener noreferrer">NOAA · 태양 위치 계산식 ↗</a><a href="https://spaceplace.nasa.gov/seasons/en/" target="_blank" rel="noopener noreferrer">NASA Space Place · 계절이 생기는 까닭 ↗</a><p>참고 자료 확인: 2026년 10월 8일. 기관이 제작하거나 인증한 앱은 아니야. 로그인 없이 사용하며 학습 기록은 이 브라우저 안에 저장돼.</p></div>`);}
async function install(){if(installPrompt){try{await installPrompt.prompt();const choice=await installPrompt.userChoice;installPrompt=null;if(choice.outcome==='accepted')toast('설치를 요청했어. 홈 화면에서 태양 연구소를 찾아봐!');}catch{installPrompt=null;installGuide();}}else installGuide();}
function installGuide(){const ua=navigator.userAgent,ios=/iPhone|iPad|iPod/.test(ua)||navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1;modal('홈 화면에 태양 연구소 추가',`<div class="install-preview"><img src="assets/icon-192.png" alt="" width="64" height="64"><div><b>하준이의 태양 연구소</b><small>버튼 하나로 과학 놀이터 열기</small></div></div><div class="help-steps"><div class="help-step"><span>1</span><div>${ios?'Safari에서 이 페이지를 열어 줘.':'Chrome 또는 Edge에서 이 페이지를 열어 줘.'} 카카오톡 안이라면 메뉴에서 ‘다른 브라우저로 열기’를 골라.</div></div><div class="help-step"><span>2</span><div>${ios?'공유 버튼 → 홈 화면에 추가를 눌러.':'브라우저 메뉴 → 앱 설치 또는 홈 화면에 추가를 눌러. PC에서는 주소창의 설치 아이콘도 확인해 봐.'}</div></div><div class="help-step"><span>3</span><div>추가를 누르면 홈 화면에서 바로 시작! 메뉴 이름은 기기마다 다를 수 있어.</div></div></div><p>첫 접속 후 저장이 완료되면 기본 실험·게임·퀴즈를 오프라인에서도 사용할 수 있어. 참고 링크와 일부 기기의 음성에는 인터넷이 필요해.</p><button class="secondary wide" data-action="copy-link" style="margin:17px 0">앱 주소 복사</button>`);}
const actions={
  'play':togglePlay,'capture':capture,'time-help':timeHelp,'check-mission':checkMission,
  'listen-lab':()=>speak('태양의 고도는 지평선과 태양을 향한 선 사이의 각도야. 우리나라에서 태양이 남쪽 하늘에 와 하루 중 가장 높아질 때를 남중이라고 해. 이때의 태양 고도가 남중고도야. 태양 고도가 높아지면 같은 막대의 그림자는 짧아져.'),
  'game-submit':submitGame,'game-next':nextGame,'game-reset':()=>{game={round:0,guess:45,submitted:false,stars:0,done:false,targets:[20,30,45,65,75].sort(()=>Math.random()-.5)};renderGame();},
  'quiz-start':()=>startQuiz(),'quiz-review':()=>startQuiz(true),'quiz-next':nextQuiz,
  'listen-quiz':()=>{const q=QUIZ.find(q=>q.id===quizSession?.ids[quizSession.index]);if(q)speak(q.why);},
  'listen-summary':()=>speak('첫째, 태양 고도는 거리가 아니라 각도야. 둘째, 태양이 남중할 때 하루 중 가장 높고 그림자는 가장 짧아. 셋째, 우리나라의 남중고도는 하지 무렵 가장 높고 동지 무렵 가장 낮아.'),
  'reset-confirm':()=>modal('학습 기록을 처음부터 시작할까?',`<p>이 브라우저의 배지, 퀴즈, 게임 최고 기록, 관찰 노트가 모두 지워져. 되돌릴 수 없어.</p><button class="secondary wide" data-action="reset-all" style="margin:20px 0">모두 지우고 새로 시작하기</button>`),
  'reset-all':()=>{progress=fresh();quizSession=null;game={round:0,guess:45,submitted:false,stars:0,done:false,targets:[30,65,45,75,20]};activeMission=0;lastMissionMessage='';save();$('#dialog').close();navigate('lab');toast('새 연구 노트를 펼쳤어. 첫 발견부터 시작해 보자!');},
  'copy-link':async()=>{try{await navigator.clipboard.writeText(location.href.split('#')[0]);toast('앱 주소를 복사했어.');}catch{toast('주소창의 앱 주소를 길게 눌러 복사해 줘.');}},
};
document.addEventListener('click',e=>{
  const b=e.target.closest('button');if(!b||b.disabled)return;
  if(b.dataset.tab)navigate(b.dataset.tab,true);
  else if(b.dataset.go)navigate(b.dataset.go,true);
  else if(b.dataset.action)actions[b.dataset.action]?.();
  else if(b.dataset.season){pause();season=b.dataset.season;updateLab();}
  else if(b.dataset.time){pause();time=Number(b.dataset.time);updateLab();}
  else if(b.dataset.mission){activeMission=Number(b.dataset.mission);lastMissionMessage='';updateMissions();}
  else if(b.dataset.exploreSeason){season=b.dataset.exploreSeason;time=12;navigate('lab',true);}
  else if(b.dataset.tilt){tilt=b.dataset.tilt==='yes';updateEarth();}
  else if(b.dataset.step&&!game.submitted){game.guess=Math.max(5,Math.min(85,game.guess+Number(b.dataset.step)));$('#guess-number').textContent=`${game.guess}°`;$('#guess').value=game.guess;}
  else if(b.dataset.answer!==undefined)answerQuiz(Number(b.dataset.answer));
  else if(b.dataset.deleteNote){progress.notes=progress.notes.filter(n=>n.id!==b.dataset.deleteNote);save();renderNotes();toast('관찰 기록 하나를 지웠어.');}
});
$('#screen').addEventListener('input',e=>{if(e.target.id==='time'){pause();time=Number(e.target.value);updateLab();}else if(e.target.id==='energy'){energyAngle=Number(e.target.value);updateEnergy();}else if(e.target.id==='guess'){game.guess=Number(e.target.value);$('#guess-number').textContent=`${game.guess}°`;}});
$('#screen').addEventListener('change',e=>{if(e.target.id==='city'){city=e.target.value;pause();tab==='lab'?updateLab():renderSeasons();}else if(e.target.id==='height'){height=Number(e.target.value);updateLab();}else if(e.target.id==='show-angle'){showAngle=e.target.checked;updateLab();}});
$('#sound').addEventListener('click',()=>{progress.sound=!progress.sound;save();if(progress.sound)chime();else {window.speechSynthesis?.cancel();if(audioContext)audioContext.suspend();}toast(progress.sound?'소리를 켰어. 듣기 버튼으로 설명도 들어 봐.':'소리를 껐어.');});
$('#install').addEventListener('click',install);$('#help').addEventListener('click',help);$('#sources').addEventListener('click',sources);$('#close-dialog').addEventListener('click',()=>$('#dialog').close());
$('#dialog').addEventListener('click',e=>{if(e.target===$('#dialog')){const r=$('#dialog').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('#dialog').close();}});
window.addEventListener('hashchange',()=>navigate(location.hash.slice(1)));
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;});window.addEventListener('appinstalled',()=>{$('#install').textContent='설치 완료';$('#install').disabled=true;});
document.addEventListener('visibilitychange',()=>{if(document.hidden){pause();window.speechSynthesis?.cancel();}});
if('serviceWorker'in navigator&&location.protocol==='https:')navigator.serviceWorker.register('./sw.js',{scope:'./'}).catch(()=>{});
if(window.matchMedia('(display-mode: standalone)').matches){$('#install').textContent='앱 실행 중';$('#install').disabled=true;}
updateHeader();navigate(location.hash.slice(1)||'lab');
