'use client';
import { useCallback,useEffect,useMemo,useRef,useState } from 'react';
import { BookOpen,Check,CheckCheck,ChevronLeft,Flame,Gamepad2,Headphones,HelpCircle,Leaf,Lock,Map,RefreshCw,Sparkles,Star,Volume2,X,Zap } from 'lucide-react';
import { Tabs,TabsList,TabsTrigger,TabsContent } from '@/components/ui/tabs';
import { Progress } from '@/components/ui/progress';
import { Dialog,DialogContent,DialogTitle,DialogDescription } from '@/components/ui/dialog';
import { Toaster } from '@/components/ui/sonner';
import { toast } from 'sonner';
import { kanji,chapters,type Kanji } from '@/lib/curriculum';
import { chapterArt,memorySymbols } from '@/lib/art';
import { dayKey,shuffle,type ProgressState } from '@/lib/learning';
const empty:ProgressState={cards:[],days:[],xp:0};
const ranks=['첫걸음 탐험가','숲길 탐험가','한자 수집가','단어 발견가','일본어 탐험가','기억의 달인','칸지 마스터'];
function Speaker({text,label='일본어 듣기'}:{text:string;label?:string}){
 function speak(){
  if(!('speechSynthesis'in window)){toast.info('이 브라우저는 음성을 지원하지 않아. 화면의 일본어와 읽기 도움말로 계속할 수 있어.');return;}
  const voices=window.speechSynthesis.getVoices(),voice=voices.find(v=>v.lang.toLowerCase().startsWith('ja'));
  if(!voice){toast.info('일본어 음성이 아직 준비되지 않았어. 기기의 음성 설정에서 일본어 음성을 설치한 뒤 다시 눌러 줘.');return;}
  window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.voice=voice;u.lang='ja-JP';u.rate=.78;u.onerror=()=>toast.info('소리가 나오지 않으면 미디어 음량과 일본어 음성 설정을 확인해 줘.');window.speechSynthesis.speak(u);
 }
 return <button className="sound-button" onClick={speak} aria-label={label}><Volume2 size={19}/><span>{label}</span></button>;
}
function Trace({char}:{char:string}){
 const canvas=useRef<HTMLCanvasElement>(null);const active=useRef(false);
 function pos(e:React.PointerEvent<HTMLCanvasElement>){const r=e.currentTarget.getBoundingClientRect();return [(e.clientX-r.left)*320/r.width,(e.clientY-r.top)*260/r.height];}
 function clear(){canvas.current?.getContext('2d')?.clearRect(0,0,320,260);}
 useEffect(clear,[char]);
 return <details className="trace"><summary>손가락으로 모양 그려 보기 <span>선택</span></summary><div className="trace-board"><span lang="ja">{char}</span><canvas ref={canvas} width={320} height={260} aria-label={`${char} 자유 연습장`} onPointerDown={e=>{active.current=true;e.currentTarget.setPointerCapture(e.pointerId);const c=e.currentTarget.getContext('2d');if(c){const [x,y]=pos(e);c.beginPath();c.moveTo(x,y);c.strokeStyle='#227e67';c.lineWidth=9;c.lineCap='round';c.lineJoin='round';}}} onPointerMove={e=>{if(!active.current)return;const c=e.currentTarget.getContext('2d');if(c){const[x,y]=pos(e);c.lineTo(x,y);c.stroke();}}} onPointerUp={()=>active.current=false} onPointerCancel={()=>active.current=false}/></div><div className="trace-foot"><small>모양 연습장이야. 획순이나 글씨를 채점하지 않아.</small><button onClick={clear}>지우기</button></div></details>;
}
function Matching({learned}:{learned:Kanji[]}){
 const [deck,setDeck]=useState<{key:string;id:string;text:string;type:string}[]>([]),[open,setOpen]=useState<string[]>([]),[matched,setMatched]=useState<string[]>([]),[moves,setMoves]=useState(0),[message,setMessage]=useState('');
 const timer=useRef<ReturnType<typeof setTimeout>|null>(null);
 useEffect(()=>()=>{if(timer.current)clearTimeout(timer.current);},[]);
 const begin=()=>{if(timer.current)clearTimeout(timer.current);const picks=shuffle(learned).slice(0,4);setDeck(shuffle(picks.flatMap(k=>[{key:k.id+'a',id:k.id,text:k.char,type:'char'},{key:k.id+'b',id:k.id,text:k.meaning,type:'meaning'}])));setOpen([]);setMatched([]);setMoves(0);setMessage('같은 뜻의 한자와 한국어를 찾아봐.');};
 function flip(key:string){if(open.length===2||open.includes(key)||matched.includes(key))return;const n=[...open,key];setOpen(n);if(n.length===2){setMoves(x=>x+1);const[a,b]=n.map(k=>deck.find(c=>c.key===k)!);if(a.id===b.id){setMatched(v=>[...v,...n]);setOpen([]);setMessage(`${a.type==='char'?a.text:b.text}, 짝을 찾았어!`);}else{setMessage('괜찮아. 위치를 기억하고 다시 찾아봐.');timer.current=setTimeout(()=>setOpen([]),900);}}}
 const finished=deck.length>0&&matched.length===deck.length;
 return <section className="match-panel"><div className="section-eyebrow"><Gamepad2 size={18}/> MEMORY LAB</div><h2>기억의 짝을 찾아라</h2><p>배운 한자와 뜻을 연결해 봐. 시간 제한은 없어.</p>{learned.length<4?<div className="empty-box"><img className="game-lock-art" src="/images/forest-adventure.webp" alt="숲에서 다음 모험을 기다리는 여우" width="720" height="480"/><Lock size={32}/><h3>한자 4개를 만나면 열려!</h3><p>지금까지 {learned.length}개를 발견했어. 모험에서 조금만 더 배워 보자.</p></div>:<><div className="match-toolbar"><span>{matched.length/2} / {deck.length/2||4}쌍 · {moves}번 시도</span><button className="secondary" onClick={begin}>{deck.length?'새 게임':'짝맞추기 시작'}</button></div><div className="match-grid">{deck.map(c=><button key={c.key} aria-label={matched.includes(c.key)?`찾은 짝 ${c.text}`:open.includes(c.key)?c.text:'뒤집힌 카드'} className={`memory-card ${c.type} ${open.includes(c.key)||matched.includes(c.key)?'revealed':''} ${matched.includes(c.key)?'matched':''}`} onClick={()=>flip(c.key)} disabled={matched.includes(c.key)}>{open.includes(c.key)||matched.includes(c.key)?c.text:<span>字<small>KANJI QUEST</small></span>}</button>)}</div><p className="match-message" aria-live="polite">{finished?`모든 짝을 찾았어! ${moves}번 만에 성공.`:message}</p><small>기억 놀이는 자유 연습이야. 복습 일정과 경험치는 바뀌지 않아.</small></>}</section>;
}
export default function Home(){
 const [data,setData]=useState<ProgressState>(empty),[loading,setLoading]=useState(true),[loadError,setLoadError]=useState(''),[tab,setTab]=useState('adventure');
 const [active,setActive]=useState<Kanji|null>(null),[stage,setStage]=useState(0),[choices,setChoices]=useState<string[]>([]),[answer,setAnswer]=useState<string|null>(null),[mistakes,setMistakes]=useState(0),[eventId,setEventId]=useState(''),[saving,setSaving]=useState(false),[saveError,setSaveError]=useState(''),[earned,setEarned]=useState(0),[saved,setSaved]=useState(false);
 const [detail,setDetail]=useState<Kanji|null>(null),[help,setHelp]=useState(false),[now,setNow]=useState(Date.now()),[collectionFilter,setCollectionFilter]=useState('all');
 const panel=useRef<HTMLDivElement>(null),answerLock=useRef(false);
 const load=useCallback(async()=>{setLoading(true);setLoadError('');try{const r=await fetch('/api/progress',{cache:'no-store'});if(!r.ok)throw new Error();setData(await r.json());}catch{setLoadError('기록을 불러오지 못했어. 연결을 확인하고 다시 눌러 줘.');}finally{setLoading(false);}},[]);
 useEffect(()=>{void load();if('speechSynthesis'in window){window.speechSynthesis.getVoices();}const timer=setInterval(()=>setNow(Date.now()),30000);return()=>clearInterval(timer);},[load]);
 const learned=useMemo(()=>kanji.filter(k=>data.cards.some(c=>c.id===k.id)),[data.cards]);
 const due=useMemo(()=>data.cards.filter(c=>c.due<=now).sort((a,b)=>a.due-b.due),[data.cards,now]);
 const next=kanji.find(k=>!data.cards.some(c=>c.id===k.id));
 const daily=data.days.find(d=>d.day===dayKey())?.count??0;
 const dailyNew=data.cards.filter(c=>c.firstDay===dayKey()).length;
 const rankIndex=Math.min(6,Math.floor(learned.length/10));
 const target=active?(stage===1?active.meaning:stage===2?active.char:active.kana):'';
 const correct=answer!==null&&answer===target;
 const previewCard=due.length?kanji.find(k=>k.id===due[0].id):next;
 const currentArt=chapterArt[(active??previewCard)?.chapter??11];
 const todayXP=data.days.find(d=>d.day===dayKey())?.xp??0;
 function prepare(k:Kanji,step:number){answerLock.current=false;setAnswer(null);const field=step===1?'meaning':step===2?'char':'kana';const t=k[field];const near=kanji.filter(x=>x.chapter===k.chapter&&x[field]!==t).map(x=>x[field]);const all=kanji.filter(x=>x[field]!==t).map(x=>x[field]);const others=shuffle(Array.from(new Set([...near,...all]))).slice(0,3);setChoices(shuffle([t,...others]));setStage(step);}
 function start(k:Kanji){setActive(k);setStage(0);setMistakes(0);setAnswer(null);setEventId(typeof crypto.randomUUID==='function'?crypto.randomUUID():Array.from(crypto.getRandomValues(new Uint32Array(4))).map(n=>n.toString(16).padStart(8,'0')).join('-'));setSaveError('');setSaved(false);setEarned(0);setTab('adventure');if(data.cards.some(c=>c.id===k.id))prepare(k,1);setTimeout(()=>panel.current?.scrollIntoView({behavior:'smooth',block:'start'}),30);}
 function startNext(){const c=due.length?kanji.find(k=>k.id===due[0].id):next;if(c)start(c);else toast.success('오늘 복습까지 끝났어. 도감에서 자유롭게 다시 볼 수 있어!');}
 function choose(v:string){if(answerLock.current||answer!==null)return;answerLock.current=true;setAnswer(v);if(v!==target)setMistakes(x=>x+1);}
 async function finish(){if(saving||saved||!active)return;setSaving(true);setSaveError('');try{const r=await fetch('/api/progress',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:active.id,eventId,mistakes})});if(!r.ok)throw new Error();const body=await r.json() as ProgressState & {earned:number};setData(body);setEarned(body.earned);setSaved(true);setNow(Date.now());}catch{setSaveError('저장 연결이 끊겼어. 이 화면에서 저장을 다시 눌러 줘.');}finally{setSaving(false);}}
 function nextStep(){if(!active)return;if(stage<3)prepare(active,stage+1);else{setStage(4);void finish();}}
 function closeMission(){if(saving)return;if(stage>0&&stage<4&&!window.confirm('이번 글자는 아직 완료하지 않았어. 모험 지도로 돌아갈까?'))return;if(stage===4&&!saved&&!window.confirm('이번 결과가 아직 저장되지 않았어. 저장하지 않고 나갈까?'))return;setActive(null);}
 useEffect(()=>{
 const ctx=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options:unknown)=>Promise<void>|void}}).modelContext;if(!ctx?.registerTool)return;const controller=new AbortController();
 try{Promise.resolve(ctx.registerTool({name:'read_learning_progress',title:'학습 진도 확인',description:'하준이의 한자 발견 수, 오늘 학습 수와 복습할 글자를 읽습니다.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('No arguments accepted');return{learned:learned.length,total:60,today:daily,due:due.map(c=>kanji.find(k=>k.id===c.id)?.char)};}},{signal:controller.signal})).catch(()=>{});}catch{}return()=>controller.abort();
 },[learned.length,daily,due]);
 return <><Toaster position="top-center"/><div className="app-shell"><header className="topbar"><a href="/" className="brand" aria-label="칸지 퀘스트 홈"><img className="brand-icon" src="/icon-v2.svg" alt="" width="47" height="49"/><div>칸지 퀘스트<small>HAJUN’S JAPANESE ADVENTURE</small></div></a><div className="header-right"><span className="xp-pill"><Zap size={17}/>{data.xp} XP</span><button className="icon-button" aria-label="학습 방법" onClick={()=>setHelp(true)}><HelpCircle size={22}/></button><span className="avatar">하</span></div></header>
 <main><div className="greeting"><div><span className="eyebrow">하준이의 일본어 탐험 노트</span><h1>한 글자씩, 일본어가 보여!</h1></div><div className="rank"><Leaf size={18}/>{ranks[rankIndex]}</div></div>
 <Tabs value={tab} onValueChange={v=>{if(active){toast.info('진행 중인 미션을 마치거나 모험 지도로 돌아가 줘.');return;}setTab(v);}}><TabsList className="main-tabs"><TabsTrigger value="adventure"><Map/>오늘의 모험</TabsTrigger><TabsTrigger value="game"><Gamepad2/>기억 게임</TabsTrigger><TabsTrigger value="collection"><BookOpen/>한자 도감 <span>{learned.length}</span></TabsTrigger></TabsList>
 {loadError?<div className="error-box" role="alert"><p>{loadError}</p><button className="primary" onClick={load}>다시 불러오기</button></div>:loading?<div className="loading-box" role="status"><RefreshCw className="spin"/>모험 기록을 불러오는 중…</div>:<>
 <TabsContent value="adventure"><div className="adventure-grid"><div className="main-column"><div className="quest-panel" ref={panel}>
 {!active?<><div className="panel-top"><span className="section-eyebrow"><span className="live-dot"/>{due.length?'다시 만날 시간':'오늘의 한 글자'}</span><span className="mini-label">약 2분 / 한 글자</span></div><div className="quest-intro"><div className="quest-art"><img className="adventure-image" src={currentArt.src} alt={currentArt.alt} width="720" height="480" style={{objectPosition:currentArt.position}} fetchPriority="high"/><div className="kanji-tile"><span lang="ja">{due.length?kanji.find(k=>k.id===due[0].id)!.char:next?.char??'完'}</span><span className="tile-tag">{due.length?'RECALL':'DISCOVER'}</span></div></div><div className="quest-copy"><span className="chapter-kicker">CHAPTER {String((due.length?kanji.find(k=>k.id===due[0].id)!.chapter:next?.chapter??11)+1).padStart(2,'0')}</span><h2>{due.length?'기억을 다시 깨워 볼까?':next?chapters[next.chapter][0]:'60글자 탐험 완료!'}</h2><p>{due.length?`${due.length}개의 글자가 하준이를 기다리고 있어. 기억나는 만큼 떠올려 보자.`:next?`${next.char}에는 어떤 뜻이 숨어 있을까? 모양을 보고, 소리를 듣고, 직접 맞혀 봐.`:'이제 아는 글자가 60개야. 복습과 기억 게임으로 더 친해져 보자.'}</p><button className="primary big" onClick={startNext} disabled={!next&&!due.length}><Sparkles size={20}/>{due.length?'복습 미션 시작':next?'한 글자 미션 시작':'오늘의 미션 완료'}</button></div></div><div className="learning-loop"><span><span>01</span>발견하기</span><span><span>02</span>떠올리기</span><span><span>03</span>다시 만나기</span></div></>:
 <><div className="panel-top"><button className="back-button" onClick={closeMission} disabled={saving}><ChevronLeft size={18}/>모험 지도</button><span className="mini-label">{stage===0?'처음 만나기':stage===4?'미션 결과':`기억 미션 ${stage} / 3`}</span></div><Progress className="mission-progress" value={stage*25} aria-label="현재 한자 미션 진행률"/>
 {stage===0?<div className="learn-view"><div className="learn-scene"><img src={currentArt.src} alt={currentArt.alt} width="720" height="480" style={{objectPosition:currentArt.position}}/><span>글자 속으로 떠나는 탐험</span></div><div className="learn-head"><span className="memory-symbol" aria-hidden="true">{memorySymbols[Number(active.id)-1]}</span><div className="learn-character" lang="ja">{active.char}</div><div><span className="mini-label">이 글자의 뜻</span><h2>{active.meaning}</h2><p className="korean-reading">한국 한자 이름 · {active.korean}</p></div></div><div className="memory-hint"><Sparkles size={20}/><div><b>이렇게 기억해 봐</b><p>{active.hint}</p><small>기억을 돕는 상상이야. 어원 풀이는 아니야.</small></div></div><div className="word-box"><span className="mini-label">일본어 단어로 만나기</span><div className="word-line"><ruby lang="ja">{active.word}<rt>{active.kana}</rt></ruby><Speaker text={active.kana}/></div><p className="word-meaning">{active.wordMeaning}</p><p className="sound-hint">읽기 도움 · {active.sound}</p><small>한글은 소리를 떠올리는 힌트야. 정확한 발음은 일본어로 들어 봐.</small></div><details className="bonus"><summary>다른 단어에서는 어떻게 읽을까?</summary><p><ruby lang="ja">{active.extra}<rt>{active.extraKana}</rt></ruby><span>{active.extraMeaning}</span><Speaker text={active.extraKana} label="들어 보기"/></p><small>한자는 단어에 따라 읽는 소리가 달라져. 지금은 첫 단어 하나만 익혀도 충분해.</small></details><Trace char={active.char}/><button className="primary full" onClick={()=>prepare(active,1)}>기억 미션 시작</button></div>:
 stage===4?<div className="result-view"><div className="result-scene"><img src={currentArt.src} alt="" width="720" height="480"/></div><div className="result-star"><Star size={45}/></div><span className="section-eyebrow">MISSION COMPLETE</span><h2>{mistakes?'다시 생각해서 해냈어!':'한 글자 더 알게 됐어!'}</h2><div className="result-word"><span lang="ja">{active.char}</span><span>{active.meaning}<small lang="ja">{active.word} · {active.kana}</small></span></div><p>{!saved?'완료한 미션을 기록하고 있어.':mistakes?'헷갈렸던 글자는 10분 뒤 다시 만나자.':earned?'다음 복습 때 다시 꺼내 보면 더 오래 기억할 수 있어.':'이미 배운 글자를 한 번 더 연습했어.'}</p>{saving?<div role="status" className="save-status">모험 기록을 저장하는 중…</div>:saveError?<div role="alert" className="error-box"><p>{saveError}</p><button className="primary" onClick={finish}>결과 저장 다시 시도</button></div>:saved?<><div className="reward"><Zap/>+{earned} XP <span>기록 저장 완료</span></div>{earned===0&&<small>예정일 전의 자유 연습에는 추가 경험치가 없어.</small>}<p className="goal-note">{dailyNew>=3?'오늘 새 글자 3개 목표를 채웠어. 여기서 쉬어도 좋아!':`오늘 새 글자 ${dailyNew}/3개 · 천천히 가도 좋아.`}</p><div className="result-actions"><button className="secondary" onClick={()=>setActive(null)}>오늘은 여기까지</button><button className="primary" onClick={startNext} disabled={!next&&!due.length}>다음 한 글자</button></div></>:null}</div>:
 <div className="quiz-view"><span className="section-eyebrow">{stage===1?'뜻 연결하기':stage===2?'모양 꺼내 보기':'일본어로 읽기'}</span><h2>{stage===1?'이 한자는 어떤 뜻일까?':stage===2?'이 뜻을 가진 한자를 찾아봐.':'이 단어는 어떻게 읽을까?'}</h2><div className={`quiz-prompt ${stage===2?'meaning-prompt':''}`} lang={stage===2?'ko':'ja'}>{stage===1?active.char:stage===2?active.meaning:active.word}</div>{stage===3&&<p className="quiz-helper">처음 배운 단어의 소리를 떠올려 봐.</p>}<div className="answer-grid">{choices.map((v,i)=><button key={v} disabled={answer!==null} onClick={()=>choose(v)} className={`answer-button ${stage===2?'kanji-answer':''} ${answer!==null&&v===target?'correct':''} ${answer===v&&v!==target?'incorrect':''}`}><span className="answer-index">{i+1}</span><span lang={stage===1?'ko':'ja'}>{v}{stage===3&&<small>{kanji.find(k=>k.kana===v)?.sound}</small>}</span>{answer!==null&&v===target?<Check size={22}/>:answer===v?<X size={22}/>:null}</button>)}</div>{answer!==null?<div className={`feedback ${correct?'positive':'gentle'}`} aria-live="polite"><b>{correct?'맞았어! 기억 속에서 꺼냈네.':'괜찮아. 다시 보면 기억에 남아.'}</b><p>{active.char} = {active.meaning} · {active.word}({active.kana})</p>{!correct&&<p>{active.hint}</p>}<button className="primary full" onClick={()=>correct?nextStep():prepare(active,stage)}>{correct?(stage===3?'미션 마치기':'다음 문제'):'다시 도전'}</button></div>:<p className="no-pressure">틀려도 괜찮아. 점수가 줄거나 기회가 사라지지 않아.</p>}</div>}
 </>}
 </div>
 {!active&&<section className="chapter-section"><div className="section-heading"><h2>12개의 탐험 코스</h2><span>코스마다 5글자</span></div><div className="chapter-grid">{chapters.map((ch,i)=>{const cards=kanji.filter(k=>k.chapter===i),count=cards.filter(k=>learned.some(l=>l.id===k.id)).length;const unlocked=i===0||kanji.filter(k=>k.chapter<i).every(k=>learned.some(l=>l.id===k.id));return <button className={`chapter-card ${!unlocked?'locked':''} ${count===5?'complete':''}`} key={ch[0]} disabled={!unlocked} onClick={()=>start(cards.find(k=>!learned.some(l=>l.id===k.id))??cards[0])}><img className="chapter-art" src={chapterArt[i].src} alt="" loading="lazy" width="320" height="160" style={{objectPosition:chapterArt[i].position}}/><div className="chapter-card-top"><span>{String(i+1).padStart(2,'0')}</span>{count===5?<CheckCheck size={18}/>:!unlocked?<Lock size={16}/>:<span>{count}/5</span>}</div><h3>{ch[0]}</h3><p lang="ja">{ch[1]}</p><Progress value={count*20} aria-label={`${ch[0]} ${count}/5`}/></button>;})}</div></section>}
 </div><aside className="quest-sidebar"><section className="goal-card"><div className="aside-title"><span className="aside-icon"><Flame size={20}/></span><h2>오늘은 딱 3글자</h2></div><p>작게 배우고, 자주 만나자.</p><div className="goal-stamps">{[0,1,2].map(i=><div key={i} className={dailyNew>i?'filled':''}>{dailyNew>i?<Check size={24}/>:String(i+1).padStart(2,'0')}</div>)}</div><div className="goal-bottom"><span>새 글자 {Math.min(dailyNew,3)} / 3</span><span>오늘 +{todayXP} XP</span></div></section><section className="collection-summary"><span className="section-eyebrow">MY COLLECTION</span><div className="collection-count">{learned.length}<span>/ 60</span></div><p>하준이가 발견한 한자</p><Progress value={learned.length/60*100} aria-label="전체 한자 발견률"/><div className="mastery"><span><CheckCheck size={16}/>7일 이상 간격 단계</span><b>{data.cards.filter(c=>c.stage>=3).length}자</b></div></section><section className="review-card"><div><RefreshCw size={20}/><h2>기억 충전소</h2></div><p>{due.length?`${due.length}글자, 다시 만날 시간!`:learned.length?'아직 복습할 시간이 아니야. 편하게 쉬어도 좋아.':'배운 글자가 생기면 복습할 시간을 알려줄게.'}</p><button className="secondary full" disabled={!due.length||!!active} onClick={()=>start(kanji.find(k=>k.id===due[0].id)!)}>복습하기 {due.length>0&&<span>{due.length}</span>}</button></section><div className="side-note"><Headphones size={18}/><p>소리를 따라 말해 봐.<br/>눈과 귀가 함께 기억해!</p></div></aside></div></TabsContent>
 <TabsContent value="game"><Matching learned={learned}/></TabsContent>
 <TabsContent value="collection"><section className="collection-panel"><div className="section-heading"><div><span className="section-eyebrow">YOUR KANJI PASSPORT</span><h2>나의 한자 도감</h2></div><span>{learned.length} / 60 발견</span></div><p>카드를 누르면 뜻과 일본어 단어를 다시 볼 수 있어.</p><div className="collection-filters" role="group" aria-label="도감 보기">{[['all','전체 60자'],['learned','발견한 글자'],['due','복습할 글자']].map(([v,l])=><button key={v} aria-pressed={collectionFilter===v} className={collectionFilter===v?'selected':''} onClick={()=>setCollectionFilter(v)}>{l}</button>)}</div><div className="dictionary-grid">{kanji.filter(k=>collectionFilter==='all'||(collectionFilter==='learned'?learned.some(l=>l.id===k.id):due.some(l=>l.id===k.id))).map(k=>{const record=data.cards.find(c=>c.id===k.id);return <button key={k.id} className={`dictionary-card ${record?'discovered':''}`} onClick={()=>setDetail(k)}><span className="dictionary-id">{String(k.id).padStart(2,'0')}</span><span lang="ja" className="dictionary-char">{k.char}</span><span>{record?k.meaning:'아직 발견 전'}</span><small>{record?(record.due<=now?'복습할 시간':record.stage>=3?'기억 자라는 중':'복습 기다리는 중'):'미리 볼 수 있어'}</small></button>;})}</div>{collectionFilter!=='all'&&!kanji.some(k=>collectionFilter==='learned'?learned.some(l=>l.id===k.id):due.some(l=>l.id===k.id))&&<div className="empty-box">{collectionFilter==='learned'?'첫 한자 미션을 마치면 여기에 카드가 모여.':'지금 복습할 글자는 없어. 잘 쉬고 다시 만나자!'}</div>}</section></TabsContent>
 </>}
 </Tabs><footer><span>하준이의 칸지 퀘스트 · 기초 60자</span><button onClick={()=>setHelp(true)}>학습 방법과 자료 안내</button></footer></main></div>
 <Dialog open={!!detail} onOpenChange={o=>!o&&setDetail(null)}><DialogContent className="detail-dialog"><DialogTitle>한자 카드</DialogTitle><DialogDescription>뜻과 일본어 단어를 함께 기억해 봐.</DialogDescription>{detail&&<><div className="detail-scene"><img src={chapterArt[detail.chapter].src} alt={chapterArt[detail.chapter].alt} width="720" height="480"/></div><div className="detail-char" lang="ja">{detail.char}</div><h3>{detail.meaning}<small>{detail.korean}</small></h3><div className="word-line"><ruby lang="ja">{detail.word}<rt>{detail.kana}</rt></ruby><Speaker text={detail.kana}/></div><p>{detail.wordMeaning} · 읽기 도움 {detail.sound}</p><p className="detail-hint">{detail.hint}</p><small>기억을 돕는 상상이며 어원 설명이 아니야.</small><p className="detail-extra"><ruby lang="ja">{detail.extra}<rt>{detail.extraKana}</rt></ruby> · {detail.extraMeaning}</p>{data.cards.some(c=>c.id===detail.id)&&<button className="primary" onClick={()=>{start(detail);setDetail(null);}}>이 글자 다시 연습</button>}</>}</DialogContent></Dialog>
 <Dialog open={help} onOpenChange={setHelp}><DialogContent className="help-dialog"><DialogTitle>하준이의 첫 한자 모험</DialogTitle><DialogDescription>일본어를 더 잘 읽기 위한 작고 꾸준한 연습.</DialogDescription><div className="help-content"><h3>하루 3글자면 충분해</h3><p>모양과 뜻을 보고 → 일본어로 듣고 → 가린 뒤 퀴즈를 풀어 봐. 모르면 다시 보고 도전하면 돼. 첫 미션 완료는 30 XP, 예정된 복습은 15 XP야.</p><h3>읽는 소리는 단어랑 한 세트</h3><p>山은 山（やま·야마）에서 ‘야마’, 富士山（ふじさん·후지산）에서는 ‘산’이야. 한국 한자 이름과 일본어 발음은 따로 봐 줘. 히라가나가 아직 낯설면 한글 힌트와 듣기를 이용해.</p><h3>기억은 간격을 두고 꺼내 보기</h3><p>처음 배운 뒤 1일, 다음 성공 뒤 3일·7일·14일·30일 간격으로 복습해. 틀린 글자는 10분 뒤 다시 나와. 이 간격은 앱의 학습 규칙이며, 누구나 같은 속도로 외운다는 뜻은 아니야.</p><h3>기록과 소리</h3><p>미션을 마치고 ‘기록 저장 완료’가 보이면 진도가 저장돼. 인터넷 연결이 필요해. 이 공간은 하준이 한 명의 학습 기록을 함께 사용해. 음성은 기기에 설치된 일본어 음성을 사용하므로 기기마다 다를 수 있어.</p><h3>뜻과 단어를 확인한 자료</h3><p>일본 초등 기초 한자와 생활 일본어를 바탕으로 순서를 다시 구성했어. 그림처럼 기억하는 힌트와 문제는 이 앱을 위해 작성했어.</p><a href="https://www.mext.go.jp/a_menu/shotou/new-cs/youryou/syo/koku.htm" target="_blank" rel="noreferrer">일본 문부과학성 · 학년별 한자표</a><a href="https://www.mext.go.jp/a_menu/shotou/new-cs/1385768.htm" target="_blank" rel="noreferrer">일본 문부과학성 · 한자 음훈 자료</a><a href="https://www.irodori.jpf.go.jp/resources.html" target="_blank" rel="noreferrer">국제교류기금 · 이로도리 한자 자료</a><small>공식 기관이 제작하거나 인증한 앱은 아니야. 한글 발음 표기는 보조 힌트이며 일본어 음가를 완전히 나타내지는 못해.</small></div></DialogContent></Dialog></>;
}
