'use strict';
/* Optional field tools: same device storage and privacy model as the original trip. */
const baseItineraryView=itineraryView,baseTransportView=transportView,baseStayView=stayView,basePrepareView=prepareView,baseHelpView=helpView,baseRenderStop=renderStop,baseShowPhrase=showPhrase;
const groupPlanNames={autumn:'조잔케이 가을 코스',otaru:'오타루 코스',rain:'우천 실내 코스'};
const guideForStop={'d1-arrival':'arrival','d1-jr':'arrival','d1-hotel':'hotel','d2-stop':'bus','d2-bus-out':'bus','d2-return-stop':'bus-back','d2-bus-back':'bus-back','d3-checkout':'departure','d3-jr':'departure','d3-airport':'departure','d3-transfer':'transfer'};
let lastChanges=null,activeMeal=null,activeExpense=null,sharedPreview=null,offlinePlayer=null;
function fieldDialog(){let d=document.getElementById('field-dialog');if(!d){d=document.createElement('dialog');d.id='field-dialog';document.body.appendChild(d);d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}});}return d;}
function modal(content){const d=fieldDialog();d.innerHTML='<button class="dialog-close" data-field="close" aria-label="닫기">×</button>'+content;if(!d.open)d.showModal();}
function rawItems(day=selectedDay){return TRIP.itinerary[day===1?'1-'+state.plan:String(day)];}
function nextCard(){
 const today=dateString(),date=TRIP.dates[selectedDay],preview=today!==date,now=nowLocal(),minute=now.getHours()*60+now.getMinutes();
 const list=currentItems().filter(i=>!i.skipped&&!state.done[i.id]);
 const started=preview?[]:list.filter(i=>TripTools.minutes(i.t)<=minute);
 const current=started.length?started[started.length-1]:null;
 const next=preview?list[0]:list.find(i=>TripTools.minutes(i.t)>minute);
 const focus=current||next;
 const label=preview?(today<TRIP.dates[0]?'출발 전 · 선택일 미리보기':'선택일 미리보기'):'현지 시각 '+TripTools.clock(minute)+' · 예정 일정';
 if(!focus)return `<div class="eyebrow">${label}</div><h2>선택한 날의 일정을 모두 확인했습니다</h2><p>다음 날짜를 선택하거나 호텔에서 충분히 쉬세요.</p>`;
 const delta=preview?null:TripTools.minutes(focus.t)-minute;
 let timing=preview?focus.t:delta>0?`${delta}분 후 예정`:delta===0?'지금 예정':`${-delta}분 전 시작 예정`;
 const extra=next&&current?`<div class="next-row"><span>다음 · ${next.t}</span><b>${esc(next.title)}</b></div>`:'';
 const flight=TRIP.flights.map((f,i)=>({...f,date:TRIP.dates[i<2?0:2]})).find(f=>new Date(`${f.date}T${f.dep}:00+09:00`)>new Date());
 return `<div class="now-top"><span class="eyebrow">${label}</span><span class="pill">10.${9+selectedDay}</span></div><div class="now-time">${timing}</div><h2>${esc(focus.title)}</h2><p class="small muted">${preview?'여행 당일에는 시각에 맞춰 현재·다음 일정이 바뀝니다.':'위치 추적 없이 계획 시각으로 표시합니다. 현장 상황이 다르면 일정을 조정하세요.'}</p><div class="actions">${focus.place?external(urlRoute(focus.place,focus.mode,focus.origin),icon('pin')+'길찾기','primary'):''}<button class="button" data-jump-stop="${focus.id}">일정 위치 보기</button>${guideForStop[focus.id]?`<button class="button" data-guide="${guideForStop[focus.id]}">이동 안내</button>`:''}</div>${extra}${flight?`<p class="small next-flight">다음 항공편 · ${flight.date.slice(5).replace('-','/')} ${flight.dep} ${flight.n} ${esc(flight.from)} 출발</p>`:''}`;
}
function changeNotice(){const result=TripTools.schedule(rawItems(),state.changes);const n=rawItems().filter(i=>state.changes[i.id]).length;return `<section class="day-tools"><div><strong>현장에서 일정 조정</strong><p class="small muted">관광·식사 카드에서 지연·휴식·건너뛰기를 선택하세요. 항공·예약 버스 후보·공항 도착 목표는 고정합니다.</p></div>${n?`<button class="button" data-field="reset-day">이날 조정 초기화</button>`:''}${lastChanges?'<button class="button" data-field="undo-change">직전 조정 취소</button>':''}</section>${result.warnings.length?`<div class="notice schedule-warning" role="status"><strong>고정 시각과 겹치는 일정이 있습니다</strong><ul>${result.warnings.map(w=>`<li>${esc(w)}</li>`).join('')}</ul><p>교통편 예약은 자동으로 변경되지 않습니다.</p></div>`:''}`;}
function applyChange(id,action){
 const original=Object.values(TRIP.itinerary).flat().find(i=>i.id===id);if(!original||TripTools.fixed.has(id)){toast('이 항목은 고정 시각입니다.');return;}
 const previous=JSON.parse(JSON.stringify(state.changes));const c={delay:0,rest:0,skip:false,...state.changes[id]};
 if(action==='delay')c.delay=Math.min(180,c.delay+30);
 if(action==='rest')c.rest=Math.min(120,c.rest+15);
 if(action==='skip')c.skip=true;
 if(action==='reset')delete state.changes[id];else state.changes[id]=c;
 if([0,1,2].some(d=>TripTools.schedule(rawItems(d),state.changes).overflow)){state.changes=previous;toast('자정을 넘는 조정입니다. 휴식이나 지연 시간을 줄여 주세요.');return;}
 lastChanges=previous;save();render();document.querySelector(`[data-stop-id="${id}"]`)?.scrollIntoView({block:'center'});toast('이 기기의 일정에 반영했습니다.');
}
renderStop=function(item,day,isPrint=false){
 if(item.skipped)return isPrint?'':`<article class="stop skipped" data-stop-id="${item.id}"><time class="time">${item.baseTime}</time><div class="stop-card"><span class="small muted">건너뛴 일정</span><h3>${esc(item.title)}</h3><button class="button" data-adjust="reset" data-item="${item.id}">일정 복원</button></div></article>`;
 let copy={...item};const restaurant=FOOD_PLACES.find(p=>p.id===state.food[item.id]);if(restaurant)copy={...copy,title:restaurant.name,desc:restaurant.menu+' · '+restaurant.note,meta:restaurant.budget+' · '+restaurant.hours,place:restaurant.place,url:restaurant.url,linkLabel:'매장 안내'};
 let html=baseRenderStop(copy,day,isPrint).replace('<article class="stop ',`<article data-stop-id="${item.id}" class="stop `);
 const detail=[item.t!==item.baseTime?`원래 ${item.baseTime} · 조정 후 ${item.t}`:'',item.rest?`식사·관람 뒤 휴식 ${item.rest}분 포함`:'',item.conflict?'앞 일정과 겹칩니다. 이동을 우선하세요.':''].filter(Boolean).join(' / ');
 if(isPrint)return html.replace('</article>',detail?`<p class="small">${detail}</p></article>`:'</article>');
 const controls=`${detail?`<p class="adjust-note ${item.conflict?'conflict':''}">${detail}</p>`:''}<div class="stop-tools">${item.locked?'<span class="fixed-tag">시각 고정</span>':`<button data-adjust="delay" data-item="${item.id}">30분 지연</button><button data-adjust="rest" data-item="${item.id}">휴식 15분</button><button data-adjust="skip" data-item="${item.id}">건너뛰기</button>${state.changes[item.id]?`<button data-adjust="reset" data-item="${item.id}">조정 취소</button>`:''}`}${guideForStop[item.id]?`<button data-guide="${guideForStop[item.id]}">이동 순서 보기</button>`:''}${isMeal(item)?`<button data-food-stop="${item.id}" data-food-reason="wait">줄이 길어요</button><button data-food-stop="${item.id}" data-food-reason="closed">문을 닫았어요</button>`:''}</div>`;
 return html.replace(/<\/div><\/article>$/,controls+'</div></article>');
};
function isMeal(item){return /점심|저녁/.test(item.type)&&!/준비/.test(item.type);}
itineraryView=function(){return baseItineraryView().replace('<div class="mobile-quick"',`<section class="panel now-panel" id="now-card">${nextCard()}</section><div class="mobile-quick"`).replace('<div class="timeline">',changeNotice()+'<div class="timeline">');};
function guideOverview(){return `<section class="panel section-space"><div class="subheading"><h2>저장해 두는 이동 안내</h2><span class="pill">오프라인 자료</span></div><p class="small muted">층·표지·탑승 방향을 정리한 이동 순서도입니다. 외부 지도·공식 링크는 인터넷이 필요합니다.</p><div class="guide-grid">${FIELD_GUIDES.map(g=>`<button data-guide="${g.id}"><b>${g.title}</b><span>${g.tag}</span></button>`).join('')}</div></section>`;}
transportView=function(){return guideOverview()+baseTransportView();};
function showGuide(id){const g=FIELD_GUIDES.find(g=>g.id===id);if(!g)return;modal(`<div class="eyebrow">OFFLINE FIELD GUIDE</div><h2>${g.title}</h2><p>${g.tag}</p><ol class="route-diagram" aria-label="이동 순서도">${g.stops.map((s,i)=>`<li><span>${i+1}</span><b>${s}</b></li>`).join('')}</ol>${['bus','bus-back'].includes(g.id)?'<figure class="official-map"><a href="./maps/jotetsu-stops.jpg" target="_blank" rel="noopener noreferrer"><img src="./maps/jotetsu-stops.jpg" alt="조테쓰 공식 약도: 삿포로역 27번 승차장과 조잔케이 정류장 위치" loading="lazy"></a><figcaption>눌러서 확대 · 조테쓰 공식 승차장 약도, 2026.10.04 확인<br>위치 변경 공지는 <a href="https://www.jotetsu.co.jp/bus/kappa_liner/" target="_blank" rel="noopener noreferrer">공식 안내</a>를 확인하세요.</figcaption></figure>':''}<ol class="guide-steps">${g.steps.map(s=>`<li>${s}</li>`).join('')}</ol><div class="notice small">${g.note}</div><div class="actions">${external(urlMap(g.map),'지도에서 확인')}${external(g.url,'공식 안내')}${g.extra?external(g.extra.url,g.extra.label):''}<button class="button" data-guide-copy="${g.id}">이동 안내 복사</button></div><p class="small muted">확인 2026.10.04 · 현장 공지 우선 · 약도는 축척 없음</p>`);}
function showFood(id,reason){
 activeMeal=id;const item=Object.values(TRIP.itinerary).flat().find(x=>x.id===id);if(!item)return;
 const area=id==='ot-lunch'?'otaru':id==='d2-lunch'?'jozankei':null;
 const candidates=FOOD_PLACES.filter(p=>(area?p.area===area:['hotel','station'].includes(p.area))&&p.id!==state.food[id]&&!(item.place||'').includes(p.id==='garaku'?'GARAKU':p.id==='hanamaru'?'根室花まる':'__none__'));
 candidates.sort((a,b)=>Number(b.area===(id==='d2-dinner'?'station':'hotel'))-Number(a.area===(id==='d2-dinner'?'station':'hotel')));
 modal(`<div class="eyebrow">MEAL BACKUP</div><h2>${reason==='closed'?'영업하는 대안 찾기':'대기 시간을 줄일 대안'}</h2><p class="small muted">현재 일정: ${esc(item.title)}<br>실시간 영업·대기 정보는 아닙니다. 예산은 계획용 범위이며 방문 전 공식 안내를 확인하세요.</p>${candidates.slice(0,4).map(p=>`<article class="food-option"><div class="spot-tag">${({station:'삿포로역 · 스텔라플레이스',hotel:'호텔 주변 · 시탓테',otaru:'오타루 · 운하·사카이마치',jozankei:'조잔케이 · 온천마을'})[p.area]}</div><h3>${p.name}</h3><p>${p.menu} · ${p.budget}</p><p class="small muted">${p.hours}<br>${p.note}</p><div class="actions">${external(urlRoute(p.place),'길찾기')}${external(p.url,'영업 확인')}<button class="button primary" data-food-pick="${p.id}">이 식사로 바꾸기</button></div></article>`).join('')}<p class="small muted">교체해도 식사 시간은 유지됩니다. 필요하면 일정의 ‘30분 지연’으로 조정하세요.</p>`);
}
stayView=function(){return baseStayView()+`<section class="panel section-space"><h2>식당 선택이 바뀌었나요?</h2><p>일정의 점심·저녁 카드에서 ‘줄이 길어요’ 또는 ‘문을 닫았어요’를 누르면 동선에 맞는 대안을 볼 수 있습니다.</p><button class="button" data-view="itinerary">식사 일정으로</button></section>`;};
function memberName(id){return state.members.find(m=>m.id===id)?.name||'결제자 미지정';}
expenseSummary=function(){const total=state.expenses.reduce((a,e)=>a+e.amount,0),r=TripTools.settle(state.expenses,state.members);return `<div class="money-total">${money(total)}</div><p class="small muted">기록 합계 · 입력 환율 기준 약 ₩${Math.round(total*state.rate/100).toLocaleString('ko-KR')}</p>${r.pending?`<p class="notice small">결제자 미지정 ${r.pending}건 · ${money(r.pendingAmount)}은 정산에서 제외했습니다. 해당 내역의 ‘수정’을 눌러 지정하세요.</p>`:''}`;};
expenseList=function(){return state.expenses.length?state.expenses.map(e=>`<div class="expense-row"><span>${esc(e.label)}<small>${esc(memberName(e.payer))} 결제 · ${e.split?.length||state.members.length}명 분담</small></span><b>${money(e.amount)}</b><div><button class="icon-button" data-expense-edit="${esc(e.id)}">수정</button><button class="icon-button" data-remove-expense="${esc(e.id)}" aria-label="${esc(e.label)} 지출 삭제">삭제</button></div></div>`).join(''):'<p class="empty">아직 기록한 지출이 없습니다.</p>';};
function settlementHtml(){const r=TripTools.settle(state.expenses,state.members);return `<h3>누가 누구에게 보내면 되나요?</h3>${r.transfers.length?`<ol class="settle-list">${r.transfers.map(t=>`<li><span>${esc(memberName(t.from))} <small>받는 사람: ${esc(memberName(t.to))}</small></span><b>${money(t.amount)}</b></li>`).join('')}</ol>`:'<p class="small muted">정산할 차액이 없습니다.</p>'}<p class="small muted">결제자가 지정된 ${money(r.total)} 기준. 1엔 미만은 분담 목록 앞사람부터 1엔씩 배분합니다. 실제 송금은 진행하지 않습니다.</p><button class="button" data-field="copy-settlement">정산 내역 복사</button>`;}
function expensePanel(){return `<section class="panel"><h2>일행 공동경비</h2><p class="small muted">이름은 이 기기에만 저장됩니다. 이미 저장한 지출은 결제자를 지정하면 정산에 포함됩니다.</p><details class="member-editor"><summary>일행 ${state.members.length}명 이름 바꾸기</summary><div class="member-fields">${state.members.map((m,i)=>`<label>일행 ${i+1}<input type="text" maxlength="20" data-member="${m.id}" value="${esc(m.name)}"></label>`).join('')}</div></details><div id="expense-summary" style="margin:18px 0">${expenseSummary()}</div><form id="expense-form" class="expense-form"><div class="field"><label for="expense-label">사용 내역</label><input id="expense-label" required maxlength="80" placeholder="예: 4명 저녁"></div><div class="field"><label for="expense-amount">금액 · JPY</label><input id="expense-amount" type="number" inputmode="numeric" min="1" max="10000000" step="1" required></div><div class="field form-span"><label for="expense-payer">결제한 사람</label><select id="expense-payer" required><option value="">선택하세요</option>${state.members.map(m=>`<option value="${m.id}">${esc(m.name)}</option>`).join('')}</select></div><fieldset class="form-span split-picker"><legend>함께 나눌 사람</legend>${state.members.map(m=>`<label><input name="expense-split" type="checkbox" value="${m.id}" checked>${esc(m.name)}</label>`).join('')}</fieldset><button class="button primary" type="submit" id="expense-submit">지출 기록</button><button class="button form-span" type="button" data-field="cancel-expense" hidden id="expense-cancel">수정 취소</button></form><div id="expense-list" class="expense-list">${expenseList()}</div><section id="settlement" class="settlement">${settlementHtml()}</section></section>`;}
function meetingPanel(){return `<section class="panel group-panel"><div class="subheading"><h2>일행에게 일정 보내기</h2><span class="pill">링크로 공유</span></div><p class="small muted">선택 코스·조정 일정·집합 장소와 시간을 전달합니다. 링크 생성 시점의 내용이며, 나중에 바꾸면 새 링크를 보내세요. 메모·지출·일행 이름은 포함하지 않습니다.</p><form id="meeting-form"><div class="field"><label for="meeting-place">집합 장소</label><input id="meeting-place" maxlength="80" placeholder="예: 크로스호텔 2층 프런트" value="${esc(state.meeting.place)}"></div><div class="meeting-fields"><div class="field"><label for="meeting-date">날짜</label><select id="meeting-date">${TRIP.dates.map(d=>`<option value="${d}" ${d===state.meeting.date?'selected':''}>${d}</option>`).join('')}</select></div><div class="field"><label for="meeting-time">시간 · 현지 시각</label><input id="meeting-time" type="time" value="${state.meeting.time}" required></div></div><p class="small">함께 볼 코스: <b>${groupPlanNames[state.plan]}</b></p><div class="actions"><button class="button primary" type="submit">집합 정보 저장</button><button class="button" type="button" data-field="share-group">저장한 일정 공유</button><button class="button" type="button" data-field="copy-group">공유 링크 복사</button></div><p class="small muted">예약번호·전화번호는 쓰지 마세요. 링크를 받은 사람은 집합 정보를 볼 수 있습니다.</p></form></section>`;}
prepareView=function(){let html=basePrepareView();const begin=html.indexOf('<section class="panel"><h2>현지 지출</h2>'),end=html.indexOf('<section class="panel"><h2>엔화 → 원화 계산</h2>',begin);if(begin>=0&&end>begin)html=html.slice(0,begin)+expensePanel()+html.slice(end);return html+meetingPanel();};
function refreshExpenseUi(){for(const [id,fn]of [['expense-summary',expenseSummary],['expense-list',expenseList],['settlement',settlementHtml]]){const el=document.getElementById(id);if(el)el.innerHTML=fn();}}
function editExpense(id){const e=state.expenses.find(x=>x.id===id);if(!e)return;activeExpense=id;document.getElementById('expense-label').value=e.label;document.getElementById('expense-amount').value=e.amount;document.getElementById('expense-payer').value=e.payer||'';document.querySelectorAll('[name="expense-split"]').forEach(x=>x.checked=e.split.includes(x.value));document.getElementById('expense-submit').textContent='수정 저장';document.getElementById('expense-cancel').hidden=false;document.getElementById('expense-form').scrollIntoView({block:'center'});}
function clearExpenseForm(){activeExpense=null;document.getElementById('expense-form')?.reset();const b=document.getElementById('expense-submit');if(b)b.textContent='지출 기록';const c=document.getElementById('expense-cancel');if(c)c.hidden=true;}
function encodeGroup(){const text=JSON.stringify(TripTools.shared(state));const bytes=new TextEncoder().encode(text);let binary='';bytes.forEach(x=>binary+=String.fromCharCode(x));const token=btoa(binary).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');const u=new URL('./',location.href);u.hash='share='+token;if(u.href.length>12000)throw Error('공유할 일정이 너무 깁니다. 불필요한 조정을 줄여 주세요.');return u.href;}
function decodeGroup(token){if(token.length>14000||!/^[A-Za-z0-9_-]+$/.test(token))throw Error('공유 링크가 올바르지 않습니다.');const binary=atob(token.replace(/-/g,'+').replace(/_/g,'/'));const text=new TextDecoder('utf-8',{fatal:true}).decode(Uint8Array.from(binary,c=>c.charCodeAt(0)));return TripTools.validateShare(JSON.parse(text),TRIP);}
function showShared(token){try{sharedPreview=decodeGroup(token);const s=sharedPreview;modal(`<div class="eyebrow">SHARED TRIP</div><h2>일행이 보낸 여행 일정</h2><p><b>${groupPlanNames[s.plan]}</b></p><p>${esc(s.meeting.date)} ${esc(s.meeting.time)}<br>${esc(s.meeting.place||'집합 장소 미지정')}</p><p class="small muted">적용하면 이 기기의 코스·시간 조정·식당 선택·집합 정보가 바뀝니다. 체크리스트·메모·경비는 유지됩니다. 실시간 동기화는 아닙니다.</p><div class="actions"><button class="button primary" data-field="apply-share">내 일정에 적용</button><button class="button" data-field="close">적용하지 않기</button></div>`);}catch{toast('공유 링크를 읽지 못했습니다. 일행에게 새 링크를 요청하세요.');}}
function storedAudioUrl(i){return './audio/'+String(i).padStart(2,'0')+'.mp3';}
speak=function(){const status=document.getElementById('speech-status');offlinePlayer?.pause();window.speechSynthesis?.cancel();offlinePlayer=new Audio(storedAudioUrl(currentPhrase));offlinePlayer.preload='auto';status.textContent='저장 음성을 재생합니다.';offlinePlayer.onended=()=>status.textContent='재생 완료 · 다시 들을 수 있습니다.';offlinePlayer.onerror=()=>status.textContent='음성을 불러오지 못했습니다. 인터넷 연결 후 다시 열거나 문구를 보여주세요.';const promise=offlinePlayer.play();promise?.catch(()=>{status.textContent='음성 재생을 시작하지 못했습니다. 기기 볼륨을 확인하고 다시 눌러 주세요.';});};
showPhrase=function(i){offlinePlayer?.pause();baseShowPhrase(i);document.getElementById('speech-status').textContent='일본어 저장 음성 · 첫 온라인 방문에서 오프라인 저장 완료 후 통신 없이 재생';document.querySelector('#phrase-controls [data-action="speak"]').textContent='저장 음성 듣기';};
document.getElementById('phrase-dialog').addEventListener('close',()=>offlinePlayer?.pause());
helpView=function(){return baseHelpView().replace('<div class="grid-2">','<div class="offline-callout">일본어 14문구는 음성 파일로 준비했습니다. 하단에서 오프라인 저장 완료를 확인하면 인터넷 없이 들을 수 있습니다.</div><div class="grid-2 section-space">');};
function recordMeeting(){const form=document.getElementById('meeting-form');if(!form?.reportValidity())return false;const value={place:document.getElementById('meeting-place').value,date:document.getElementById('meeting-date').value,time:document.getElementById('meeting-time').value};state.meeting=TripTools.cleanExtras({meeting:value},TRIP,state.people).meeting;save();return true;}
document.addEventListener('submit',e=>{
 if(e.target.id==='expense-form'){
  e.preventDefault();e.stopImmediatePropagation();const label=document.getElementById('expense-label').value.trim(),amount=Number(document.getElementById('expense-amount').value),payer=document.getElementById('expense-payer').value,split=[...document.querySelectorAll('[name="expense-split"]:checked')].map(x=>x.value);
  if(!label||!Number.isInteger(amount)||amount<=0||amount>10000000||!state.members.some(m=>m.id===payer)||!split.length){toast('내역·금액·결제자와 분담할 사람을 확인하세요.');return;}
  if(!activeExpense&&state.expenses.length>=500){toast('경비는 500건까지 기록할 수 있습니다.');return;}
  const entry={id:activeExpense||(crypto.randomUUID?crypto.randomUUID():String(Date.now())),label:label.slice(0,80),amount,payer,split};
  if(activeExpense)state.expenses=state.expenses.map(x=>x.id===activeExpense?entry:x);else state.expenses.push(entry);save();refreshExpenseUi();clearExpenseForm();toast('결제자와 분담 내역을 저장했습니다.');
 }else if(e.target.id==='meeting-form'){e.preventDefault();e.stopImmediatePropagation();if(recordMeeting())toast('집합 정보를 이 기기에 저장했습니다.');}
},true);
document.addEventListener('change',e=>{if(e.target.dataset.member){const m=state.members.find(x=>x.id===e.target.dataset.member);if(m){m.name=e.target.value.trim().slice(0,20)||'일행 '+(state.members.indexOf(m)+1);save();activeExpense=null;render();}}},true);
document.addEventListener('click',async e=>{
 const b=e.target.closest('button');if(!b)return;
 if(b.dataset.adjust){e.stopImmediatePropagation();applyChange(b.dataset.item,b.dataset.adjust);return;}
 if(b.dataset.guide){showGuide(b.dataset.guide);return;}
 if(b.dataset.guideCopy){const g=FIELD_GUIDES.find(g=>g.id===b.dataset.guideCopy);if(g)copyText(g.title+'\n'+g.steps.map((x,i)=>`${i+1}. ${x}`).join('\n')+'\n'+g.note);return;}
 if(b.dataset.jumpStop){document.querySelector(`[data-stop-id="${b.dataset.jumpStop}"]`)?.scrollIntoView({block:'center',behavior:'smooth'});return;}
 if(b.dataset.foodStop){showFood(b.dataset.foodStop,b.dataset.foodReason);return;}
 if(b.dataset.foodPick&&activeMeal){state.food[activeMeal]=b.dataset.foodPick;save();fieldDialog().close();render();toast('식사 후보를 바꿨습니다. 영업 여부를 확인하세요.');return;}
 if(b.dataset.expenseEdit){editExpense(b.dataset.expenseEdit);return;}
 if(b.dataset.removeExpense){e.stopImmediatePropagation();state.expenses=state.expenses.filter(x=>x.id!==b.dataset.removeExpense);if(activeExpense===b.dataset.removeExpense)clearExpenseForm();save();refreshExpenseUi();toast('지출을 삭제했습니다.');return;}
 if(!b.dataset.field)return;e.stopImmediatePropagation();
 switch(b.dataset.field){
  case'close':fieldDialog().close();break;
  case'cancel-expense':clearExpenseForm();break;
  case'undo-change':if(lastChanges){state.changes=lastChanges;lastChanges=null;save();render();}break;
  case'reset-day':if(confirm('선택한 날의 시간 조정·건너뛰기를 초기화할까요?')){lastChanges=JSON.parse(JSON.stringify(state.changes));rawItems().forEach(i=>delete state.changes[i.id]);save();render();}break;
  case'copy-settlement':{const r=TripTools.settle(state.expenses,state.members);copyText('삿포로 여행 경비 정산\n'+r.transfers.map(t=>`${memberName(t.from)} → ${memberName(t.to)}: ${money(t.amount)}`).join('\n')+`\n정산 대상 ${money(r.total)}${r.pending?' / 결제자 미지정 '+r.pending+'건 제외':''}\n송금 실행 전 일행과 확인하세요.`);break;}
  case'share-group':case'copy-group':if(recordMeeting()){try{const url=encodeGroup();if(b.dataset.field==='share-group'&&navigator.share){try{await navigator.share({title:TRIP.title+' · 일행 일정',text:groupPlanNames[state.plan],url});}catch(err){if(err.name!=='AbortError')await copyText(url);}}else await copyText(url);}catch(err){toast(err.message);}}break;
  case'apply-share':if(sharedPreview){lastChanges=null;const incoming=sharedPreview;const candidate={...state,plan:incoming.plan,changes:incoming.changes};if([0,1,2].some(d=>TripTools.schedule(TRIP.itinerary[d===1?'1-'+candidate.plan:String(d)],candidate.changes).overflow)){toast('자정을 넘는 일정 조정이 있어 적용하지 못했습니다.');break;}state.plan=incoming.plan;state.meeting=incoming.meeting;state.changes=incoming.changes;state.food=incoming.food;save();fieldDialog().close();selectedDay=1;setView('itinerary');toast('공유받은 일정을 적용했습니다.');}break;
 }
},true);
// Refresh only the current/next summary; leave form focus and editing intact.
setInterval(()=>{const el=document.getElementById('now-card');if(el&&document.visibilityState!=='hidden')el.innerHTML=nextCard();},30000);
render();
if(typeof incomingTripShare==='string'&&incomingTripShare)showShared(incomingTripShare);
