(() => {
'use strict';
const CARDS=window.QUEST_CARDS, UNITS=window.QUEST_UNITS, AREAS=window.QUEST_AREAS;
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const KEY='hajun-proverb-quest-v1', ids=new Set(CARDS.map(c=>c.id)), DAY=86400000;
const dateKey=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const fresh=()=>({version:1,xp:0,records:{},stars:[],days:[],rounds:0,perfect:0,totalAnswers:0,correctAnswers:0,daily:{date:dateKey(),cards:[],listens:[],answers:0},settings:{language:'mix',sound:true,kana:true,pron:false,englishVoice:'',japaneseVoice:''}});
const num=(x,max=1000000)=>Number.isFinite(x)?Math.max(0,Math.min(max,Math.floor(x))):0;
function sanitize(raw){
 const s=fresh(); if(!raw||typeof raw!=='object'||raw.version!==1)throw Error('잘못된 학습 기록');
 ['xp','rounds','perfect','totalAnswers','correctAnswers'].forEach(k=>s[k]=num(raw[k]));
 for(const [id,r] of Object.entries(raw.records||{})){if(!ids.has(id)||!r||typeof r!=='object')continue;s.records[id]={learned:r.learned===true,hits:num(r.hits,1000),wrong:num(r.wrong,1000),due:num(r.due,9999999999999),lastCorrect:typeof r.lastCorrect==='string'?r.lastCorrect.slice(0,10):''};}
 s.stars=Array.isArray(raw.stars)?[...new Set(raw.stars.filter(i=>ids.has(i)))]:[];
 s.days=Array.isArray(raw.days)?[...new Set(raw.days.filter(d=>typeof d==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(d)))].sort().slice(-3650):[];
 if(raw.daily?.date===dateKey())s.daily={date:dateKey(),cards:[...new Set((Array.isArray(raw.daily.cards)?raw.daily.cards:[]).filter(i=>ids.has(i)))],listens:[...new Set((Array.isArray(raw.daily.listens)?raw.daily.listens:[]).filter(i=>ids.has(i)))],answers:num(raw.daily.answers)};
 if(raw.settings){const o=raw.settings;if(['mix','en','ja'].includes(o.language))s.settings.language=o.language;['sound','kana','pron'].forEach(k=>{if(typeof o[k]==='boolean')s.settings[k]=o[k]});['englishVoice','japaneseVoice'].forEach(k=>{if(typeof o[k]==='string')s.settings[k]=o[k].slice(0,500)})}return s;
}
let state,storageOK=true;
try{const raw=localStorage.getItem(KEY);state=raw?sanitize(JSON.parse(raw)):fresh();}catch{state=fresh();storageOK=false;}
let view=['home','cards','play','passport','settings'].includes(location.hash.slice(1))?location.hash.slice(1):'home';
let collection={query:'',filter:'all',area:null},lesson=null,game=null,installPrompt=null,speechUtterance=null,voices=[],toastTimer,modalReturn=null;
const shuffle=a=>{let b=[...a];for(let i=b.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]]}return b;};
function ensureDay(){if(state.daily.date!==dateKey())state.daily={date:dateKey(),cards:[],listens:[],answers:0};}
function save(){ensureDay();try{localStorage.setItem(KEY,JSON.stringify(state));storageOK=true;}catch{if(storageOK)toast('기록을 저장하지 못했어. 설정에서 기록을 내려받아 줘.');storageOK=false;}}
function activeDay(){ensureDay();const d=dateKey();if(!state.days.includes(d))state.days.push(d);state.days.sort();}
function record(id){return state.records[id]||(state.records[id]={learned:false,hits:0,wrong:0,due:0,lastCorrect:''});}
const learned=()=>CARDS.filter(c=>state.records[c.id]?.learned);
const mastered=()=>CARDS.filter(c=>(state.records[c.id]?.hits||0)>=3);
const langPool=()=>CARDS.filter(c=>state.settings.language==='mix'||state.settings.language===c.lang);
const dueCards=()=>langPool().filter(c=>state.records[c.id]&&state.records[c.id].due<=Date.now());
const level=()=>Math.floor(state.xp/120)+1;
function streak(){const d=new Date();if(!state.days.includes(dateKey(d)))d.setDate(d.getDate()-1);let n=0;while(state.days.includes(dateKey(d))){n++;d.setDate(d.getDate()-1);}return n;}
const langTag=c=>`<span class="tag">${c.lang==='en'?'EN · 영어':'JP · 일본어'}${c.type==='사자성어'?' · 사자성어':''}</span>`;
const icons={home:'<path d="m3 10 9-7 9 7v10H3Z"/><path d="M9 20v-7h6v7"/>',cards:'<rect x="6" y="4" width="14" height="17" rx="3"/><path d="M3 16V3h12M10 9h6m-6 4h6"/>',play:'<path d="M8 7h8c5 0 7 13 3 13l-4-4H9l-4 4C1 20 3 7 8 7Z"/><path d="M7 10v5m-2-2h4m6-2h1m1 3h1"/>',passport:'<rect x="4" y="3" width="16" height="19" rx="3"/><circle cx="12" cy="10" r="4"/><path d="M8 18h8M8 10h8m-4-4v8"/>',settings:'<path d="m10 3-1 3-3 1-3 3 2 2-1 4 3 2 3 3 3-1 4 1 2-3 3-3-2-3 1-3-3-2-3-2Z"/><circle cx="12" cy="12" r="3"/>'};
const navs=[['home','탐험 지도'],['cards','속담 도감'],['play','게임 퀘스트'],['passport','나의 여권'],['settings','설정']];
const ico=(k)=>`<svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round">${icons[k]}</svg>`;
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),3800);}
function chime(good=true){if(!state.settings.sound)return;try{const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;const ctx=new AC();ctx.resume().catch(()=>{});[0,.12].forEach((t,i)=>{const o=ctx.createOscillator(),g=ctx.createGain();o.type='sine';o.frequency.value=good?[523,784][i]:[330,261][i];g.gain.setValueAtTime(.045,ctx.currentTime+t);g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+t+.19);o.connect(g);g.connect(ctx.destination);o.start(ctx.currentTime+t);o.stop(ctx.currentTime+t+.2)});setTimeout(()=>ctx.close().catch(()=>{}),500);}catch{}}
function celebrate(){chime();if(window.matchMedia?.('(prefers-reduced-motion: reduce)').matches)return;const el=$('#confetti');el.innerHTML=Array.from({length:30},(_,i)=>`<i class="confetti-piece" style="left:${Math.random()*100}%;background:${['#9880e4','#e4ef9c','#f3bc9c','#8ed6c0'][i%4]};animation-delay:${Math.random()*.25}s"></i>`).join('');setTimeout(()=>el.replaceChildren(),2200);}
function renderHeader(){ensureDay();const html=navs.map(([k,n])=>`<button class="navbtn ${view===k?'active':''}" data-do="navigate" data-view="${k}" ${view===k?'aria-current="page"':''}>${ico(k)}<span>${n}</span></button>`).join('');$('#nav').innerHTML=html;$('#mobile-nav').innerHTML=html;$('#topstats').innerHTML=`<span class="stat-pill">✦ Lv.${level()}</span><span class="stat-pill streak">🔥 ${streak()}일 연속</span><span class="stat-pill xp">⚡ ${state.xp} XP</span><span class="avatar">H</span>`;}
function render(){renderHeader();$('#main').innerHTML=({home:home,cards:cardsView,play:playView,passport:passportView,settings:settingsView}[view]||home)();if(view==='settings')fillVoices();}
function go(next){if(!navs.some(n=>n[0]===next))return;closeModal();view=next;history.replaceState(null,'',`#${next}`);render();window.scrollTo?.({top:0,behavior:'instant'});$('#main').focus({preventScroll:true});}
function languageControl(){return `<div class="segmented" aria-label="학습 언어">${[['mix','두 언어 함께'],['en','EN 영어'],['ja','JP 일본어']].map(([v,t])=>`<button data-do="language" data-value="${v}" class="${state.settings.language===v?'active':''}" aria-pressed="${state.settings.language===v}">${t}</button>`).join('')}</div>`;}
function world(a){let count=learned().filter(c=>c.area===a.id).length;return `<button class="world ${a.color}" data-do="area" data-area="${a.id}"><div class="world-top"><span>WORLD 0${a.id+1}</span><span>↗</span></div><div class="world-icon" aria-hidden="true">${a.icon}</div><h3>${a.name}</h3><p>${a.sub}</p><div class="progress" aria-label="${count}/12개 학습"><span style="width:${count/12*100}%"></span></div><div class="world-bottom"><span>${count===12?'탐험 완료!':'탐험 가능'}</span><span>${count} / 12</span></div></button>`;}
function home(){const d=state.daily;const featured=CARDS[Math.floor(Date.now()/DAY)%CARDS.length];return `<section class="hero"><div class="hero-copy"><span class="eyebrow">ENGLISH × JAPANESE</span><h1>오늘의 모험,<br><span class="accent">한 문장부터.</span></h1><p>영어와 일본어로 만나는 작은 지혜.<br>여우 루미, 고양이 모치와 함께 떠나 볼까?</p><button class="primary lime" data-do="daily">오늘의 탐험 시작 <span>→</span></button><span class="small-hint">하루 4장부터<br>부담 없이 시작!</span></div><img src="hero.svg" alt="여권을 들고 모험을 떠나는 여우 루미와 고양이 모치"></section><div class="section-head"><div><h2>어디로 떠나 볼까?</h2><p>4개의 세계 · 48개의 속담과 표현 · 모든 세계가 열려 있어</p></div><button class="text-btn" data-do="navigate" data-view="cards">전체 보기 ↗</button></div><div class="worlds">${AREAS.map(world).join('')}</div><div class="dashboard-lower"><section class="panel"><div class="panel-head"><h2>오늘의 작은 미션</h2><span class="tag">DAILY QUEST</span></div>${[[d.cards.length,4,'📚','카드 4장 익히기','새로운 문장을 만나 봐'],[d.answers,5,'🎯','퀴즈 5문제 도전','틀려도 괜찮아, 연습이니까'],[d.listens.length,2,'🎧','다른 문장 2개 듣기','듣고 소리 내어 따라 해 봐']].map(([v,t,i,n,h])=>`<div class="mission"><span class="mission-ico">${v>=t?'✓':i}</span><div><strong>${n}</strong><p>${h}</p></div><span class="mission-right">${Math.min(v,t)} / ${t}</span></div>`).join('')}</section><section class="panel featured"><div class="panel-head"><h2>오늘의 한 문장</h2><span class="tag">${featured.lang==='en'?'ENGLISH':'日本語'}</span></div><div><div class="featured-quote" lang="${featured.lang}">${esc(featured.text)}</div><p>${esc(featured.meaning)}</p></div><div class="featured-foot"><button class="text-btn" data-do="detail" data-id="${featured.id}">문장 만나 보기 →</button><button class="circle-btn" data-do="speak" data-id="${featured.id}" aria-label="오늘의 문장 듣기">▶</button></div></section></div>${dueCards().length?`<div class="callout">🔁 <strong>다시 만나면 더 오래 기억해.</strong> 복습할 카드 ${dueCards().length}장이 기다려. <button class="text-btn" data-do="review">복습하기 →</button></div>`:''}`;}
function cardTile(c){const r=state.records[c.id];return `<article class="collect-card"><div class="card-cover ${AREAS[c.area].color}"><span class="card-no">NO. ${String(CARDS.indexOf(c)+1).padStart(2,'0')}</span><span aria-hidden="true">${c.icon}</span><button class="star ${state.stars.includes(c.id)?'saved':''}" data-do="star" data-id="${c.id}" aria-label="${esc(c.text)} 즐겨찾기" aria-pressed="${state.stars.includes(c.id)}">${state.stars.includes(c.id)?'★':'☆'}</button></div><button class="card-main" data-do="detail" data-id="${c.id}">${langTag(c)}<h3 lang="${c.lang}">${esc(c.text)}</h3><p>${esc(c.title)}</p></button><div class="card-base"><span class="${r?.learned?'learned':''}">${r?.hits>=3?'✦ 마스터':r?.learned?'✓ 배운 카드':'새로운 카드'}</span><span>${r?.hits||0}/3 정답</span></div></article>`;}
function filteredCards(){const q=collection.query.trim().toLowerCase();return langPool().filter(c=>(collection.area===null||c.area===collection.area)&&(collection.filter!=='star'||state.stars.includes(c.id))&&(collection.filter!=='new'||!state.records[c.id]?.learned)&&(collection.filter!=='review'||(state.records[c.id]&&state.records[c.id].due<=Date.now()))&&(collection.filter!=='master'||state.records[c.id]?.hits>=3)&&(!q||[c.text,c.meaning,c.pron,c.kana,c.title].join(' ').toLowerCase().includes(q)));}
function cardGrid(){const list=filteredCards();return list.length?list.map(cardTile).join(''):`<div class="empty"><span>🔎</span><h2>아직 카드가 없어</h2><p>검색어나 필터를 바꿔 봐. 즐겨찾기는 ☆을 누르면 돼.</p></div>`;}
function cardsView(){const a=collection.area!==null?AREAS[collection.area]:null;return `<div class="page-title"><div><div class="eyebrow">MY PROVERB COLLECTION</div><h1>속담 도감</h1><p>문장을 수집하고, 나만의 말로 만들어 봐.</p></div><button class="secondary" data-do="review">🔁 복습 카드 ${dueCards().length}</button></div>${a?`<div class="island-header ${a.color}"><span>${a.icon}</span><div><h2>${a.name}</h2><p>영어 6개 + 일본어 6개</p></div><button class="text-btn" style="margin-left:auto" data-do="area-learn" data-area="${a.id}">이 세계 배우기 →</button></div>`:''}<div class="toolbar">${languageControl()}<input class="search" id="search" type="search" value="${esc(collection.query)}" placeholder="속담, 뜻, 발음으로 찾기" aria-label="속담 검색"><select id="card-filter" class="filter" aria-label="카드 필터">${[['all','모든 카드'],['new','처음 만나는 카드'],['star','★ 즐겨찾기'],['review','지금 복습할 카드'],['master','✦ 마스터 카드']].map(([v,n])=>`<option value="${v}" ${collection.filter===v?'selected':''}>${n}</option>`).join('')}</select>${a?'<button class="text-btn" data-do="all-areas">전체 세계 보기</button>':''}</div><div id="card-grid" class="card-grid">${cardGrid()}</div>`;}
function playView(){return `<div class="page-title"><div><div class="eyebrow">LEARN BY PLAYING</div><h1>게임 퀘스트</h1><p>한 판에 최대 5문제. 틀린 문제는 복습 카드로 돌아와.</p></div></div><div class="toolbar">${languageControl()}</div><div class="games">${[['meaning','🎯','뜻 맞히기','문장이 전하는 지혜를 찾아 봐.','첫 퀘스트로 추천','mint'],['build','🧩','문장 조립소','흩어진 조각을 순서대로 연결해.','단어 순서 익히기','peach'],['listen','🎧','귀로 찾는 속담','문장을 듣고 정답 카드를 골라.','발음에 귀 기울이기','lilac'],['situation','💬','이럴 땐 이 속담','일상 속 장면에 어울리는 말을 찾아.','실전 상황 퀴즈','blue']].map(([m,i,t,p,tag,color])=>`<button class="game-tile" data-do="game" data-mode="${m}"><div class="game-art ${color}">${i}</div><div><h2>${t}</h2><p>${p}</p><span class="tag">${tag} →</span></div></button>`).join('')}</div><div class="callout">💡 <strong>먼저 배우고, 게임으로 기억해.</strong><br>배운 카드가 4개 이상이면 그 카드에서 먼저 출제해. 아직 없다면 시작의 숲 카드로 연습해. 시간제한은 없어.</div><section class="panel"><div class="panel-head"><h2>다시 풀면 내 것이 돼</h2><button class="text-btn" data-do="wrong-game">오답 재도전 →</button></div><p class="help">틀린 뒤 아직 정답을 맞히지 못한 카드 ${CARDS.filter(c=>state.records[c.id]?.wrong>0).length}개 · 퀴즈 정답 세 번이면 마스터 표시가 생겨.</p></section>`;}
function passportView(){const l=learned().length,m=mastered().length;const badges=[['🌱','첫 발자국','카드 1개 배우기',l>=1],['🌏','두 언어 여행자','영어·일본어 각각 1개 배우기',learned().some(c=>c.lang==='en')&&learned().some(c=>c.lang==='ja')],['🎮','퀘스트 클리어','퀴즈 한 판 끝내기',state.rounds>=1],['💯','퍼펙트 라운드','퀴즈 한 판 모두 정답',state.perfect>=1],['🧠','기억의 마스터','카드 6개 마스터',m>=6],['🏆','세계 탐험가','카드 48개 모두 배우기',l===48]];return `<div class="page-title"><div><div class="eyebrow">MY ADVENTURE PASSPORT</div><h1>나의 여권</h1><p>작은 배움이 차곡차곡, 하준이만의 탐험 기록.</p></div></div><section class="passport-hero"><img src="icon.svg" alt="루미"><div><span class="eyebrow" style="color:#c3b8dc">PROVERB EXPLORER</span><h2>Lv.${level()} ${level()<4?'새싹 탐험가':level()<9?'지혜 수집가':'언어 모험가'}</h2><span style="font-size:12px;color:#cfc8de">다음 레벨까지 ${120-state.xp%120} XP</span><div class="progress"><span style="width:${state.xp%120/120*100}%"></span></div></div></section><div class="stats-grid">${[[l,'배운 카드 / 48'],[m,'마스터 카드'],[state.rounds,'완료한 퀴즈'],[state.days.length,'함께한 날']].map(([v,t])=>`<div class="stat-box"><b>${v}</b><span>${t}</span></div>`).join('')}</div><div class="section-head"><div><h2>나의 탐험 배지</h2><p>랜덤 뽑기 없이, 배운 만큼 받는 작은 기념품.</p></div><span class="tag">${badges.filter(b=>b[3]).length} / 6</span></div><div class="badges">${badges.map(([i,t,d,e])=>`<div class="badge ${e?'earned':''}"><span class="emblem">${i}</span><strong>${e?'✓ ':''}${t}</strong><p>${d}</p></div>`).join('')}</div><div class="section-head"><h2>세계별 발자국</h2></div><div class="worlds">${AREAS.map(world).join('')}</div><div class="callout">📝 학습 기록은 <strong>지금 사용하는 브라우저</strong>에 저장돼. 다른 기기로 옮길 때는 설정에서 기록을 내려받아 가져오면 돼.</div>`;}
function toggle(k,t){return `<div class="setting-row"><label for="toggle-${k}">${t}</label><button id="toggle-${k}" class="toggle ${state.settings[k]?'on':''}" role="switch" aria-checked="${state.settings[k]}" aria-label="${t}" data-do="toggle" data-key="${k}"><span></span></button></div>`;}
function settingsView(){return `<div class="page-title"><div><div class="eyebrow">MAKE IT YOURS</div><h1>내게 맞게 설정</h1><p>읽는 방법도, 듣는 목소리도 편한 쪽으로.</p></div><button class="secondary" data-do="install">↓ 홈 화면에 설치</button></div><div class="settings-grid"><section class="panel"><h2>읽기와 소리</h2>${toggle('sound','정답·완료 효과음')}${toggle('kana','일본어 히라가나 표시')}${toggle('pron','한글 발음 도움말')}<p class="help">한글 발음은 대략적인 읽기 도움말이야. 정확한 소리는 듣기 버튼으로 익혀 봐.</p><div style="margin-top:20px"><label for="en-voice" class="subtle">영어 목소리</label><select id="en-voice" class="voice-select"></select><label for="ja-voice" class="subtle">일본어 목소리</label><select id="ja-voice" class="voice-select"></select><button class="audio-btn" data-do="speak" data-id="en1">영어 소리 확인</button> <button class="audio-btn" data-do="speak" data-id="ja1">일본어 소리 확인</button><p id="voice-status" class="help"></p></div></section><section class="panel"><h2>나의 학습 기록</h2><p class="help">회원가입 없이 쓸 수 있어. 기록은 브라우저마다 따로 보관되며 자동으로 기기 간 동기화되지 않아.</p><div class="record-row"><span>기록 파일로 내려받기</span><button data-do="export">내려받기 ↓</button></div><div class="record-row"><span>다른 기기의 기록 가져오기</span><button data-do="import">가져오기 ↑</button></div><input id="import-file" type="file" accept=".json,application/json" hidden><div class="record-row"><span>처음부터 다시 시작</span><button data-do="reset" style="color:#b46873">기록 초기화</button></div><p class="help">가져오기는 현재 기록을 교체해. 초기화 전에는 기록을 내려받는 걸 추천해.</p><p class="help">저장 상태: ${storageOK?'이 브라우저에 자동 저장 중':'저장할 수 없음 · 기록을 내려받아 보관해 줘'}</p></section><section class="panel"><h2>어떻게 공부할까?</h2><p class="help">① 오늘의 탐험으로 4장을 만나.<br>② 뜻을 보기 전에 어떤 의미인지 짐작해.<br>③ 문장을 듣고 직접 소리 내어 말해.<br>④ 퀴즈를 풀고 다음 날 복습해.</p><p class="help">카드를 익히면 같은 날 카드당 10 XP, 퀴즈 정답은 15 XP를 받아. 정답을 맞힌 카드는 1일 → 3일 → 7일 간격으로 복습해. 틀린 카드는 바로 다시 연습할 수 있어.</p><p class="help">일본어 한자를 모르면 히라가나와 한글 도움말을 켜 봐. 짧은 덩어리로 문장을 조립하면 읽기 부담도 줄어들어.</p></section><section class="panel"><h2>표현과 학습 자료</h2><p class="help">영어 24개·일본어 24개의 속담과 관용 표현을 담았어. 不言実行은 일본어 사자성어로 따로 표시했어. 두 언어의 표현은 완전히 같은 뜻이 아닐 수 있어. 카드의 ‘두 언어를 연결해 보면’을 펼쳐 차이를 확인해.</p><a class="source" href="https://dictionary.cambridge.org/dictionary/english/practice-makes-perfect" target="_blank" rel="noopener noreferrer">Cambridge Dictionary · Practice makes perfect ↗</a><a class="source" href="https://dictionary.cambridge.org/dictionary/english/actions-speak-louder-than-words" target="_blank" rel="noopener noreferrer">Cambridge Dictionary · Actions speak louder than words ↗</a><a class="source" href="https://kotobank.jp/word/七転び八起き-589160" target="_blank" rel="noopener noreferrer">コトバンク · 七転び八起き ↗</a><a class="source" href="https://kotobank.jp/word/猿も木から落ちる-512429" target="_blank" rel="noopener noreferrer">コトバンク · 猿も木から落ちる ↗</a><p class="help">한국어 풀이, 학습 장면, 예문은 이 앱을 위해 작성했어. 속담은 상황을 이해하는 지혜이지 언제나 성립하는 법칙은 아니야.</p></section></div><p class="revision">PROVERB QUEST 1.0 · 광고·결제·채팅 없음 · 음성은 기기의 읽어주기 기능을 사용해. 기기 설정에 따라 온라인 연결이 필요할 수 있어.</p>`;}
function openModal(){const m=$('#modal');if(!m.open){modalReturn=document.activeElement;m.showModal();}m.scrollTop=0;}
function closeModal(){if($('#modal').open)$('#modal').close();window.speechSynthesis?.cancel();speechUtterance=null;lesson=null;game=null;}
$('#modal').addEventListener('close',()=>{window.speechSynthesis?.cancel();lesson=null;game=null;if(modalReturn?.isConnected)modalReturn.focus({preventScroll:true});render();});
$('#modal').addEventListener('click',e=>{if(e.target===$('#modal')){const r=$('#modal').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeModal();}});
function dailyStart(){const pool=langPool(),due=dueCards(),unknown=pool.filter(c=>!state.records[c.id]?.learned);let list=[...due,...unknown].filter((c,i,a)=>a.findIndex(v=>v.id===c.id)===i).slice(0,4);if(!list.length)list=shuffle(pool).slice(0,4);startLesson(list.map(c=>c.id),'오늘의 탐험');}
function startLesson(list,label='카드 탐험'){if(!list.length){toast('지금 복습할 카드는 없어. 새로운 카드를 만나 보자!');return;}game=null;lesson={ids:list,index:0,revealed:false,label,done:0};renderLesson();openModal();}
function renderLesson(){if(!lesson)return;const c=CARDS.find(c=>c.id===lesson.ids[lesson.index]);if(!c)return;const u=UNITS[c.unit-1],other=CARDS.find(v=>v.unit===c.unit&&v.lang!==c.lang);$('#modal-body').innerHTML=`<div class="modal-top"><div><span class="tag">${esc(lesson.label)}</span> <span class="subtle">${lesson.index+1} / ${lesson.ids.length}</span></div><button class="close" data-do="close" aria-label="학습 닫기">×</button></div><div class="modal-inner"><div class="lesson-art ${AREAS[c.area].color}"><div class="art-lines"><span></span><span></span><span></span></div><span class="giant" aria-hidden="true">${c.icon}</span><div class="art-lines"><span></span><span></span><span></span></div></div><div class="lesson-label">${langTag(c)}<button class="text-btn" data-do="lesson-star" data-id="${c.id}">${state.stars.includes(c.id)?'★ 저장했어':'☆ 저장하기'}</button></div><h2 class="lesson-title" lang="${c.lang}">${esc(c.text)}</h2>${c.lang==='ja'&&state.settings.kana?`<p class="kana" lang="ja">${esc(c.kana)}</p>`:''}${state.settings.pron?`<p class="pron">${esc(c.pron)}</p><p class="reading-note">한글은 발음 도움말이야. 소리도 꼭 들어 봐.</p>`:''}<div class="audio-actions"><button class="audio-btn" data-do="speak" data-id="${c.id}">▶ 문장 듣기</button><button class="audio-btn" data-do="speak" data-id="${c.id}" data-slow="true">🐢 천천히</button><button class="audio-btn" data-do="stop-speech">■ 멈추기</button>${!state.settings.pron?'<button class="audio-btn" data-do="show-pron">가 발음 도움말</button>':''}</div>${lesson.revealed?`<div class="meaning"><div class="tiny">이런 뜻이야</div><strong>${esc(c.meaning)}</strong><p>글자 그대로: ${esc(c.literal)}</p></div><div class="situation"><h3>💭 이런 장면을 떠올려 봐</h3><p>${esc(u.situation)}</p></div><div class="words"><h3>문장 속 작은 단어</h3><div class="wordchips">${c.words.split(';').map(w=>{const p=w.split('|');return `<span class="wordchip"><b lang="${c.lang}">${esc(p[0])}</b>${p.length===3?` <small>${esc(p[1])}</small>`:''} · ${esc(p.at(-1))}</span>`}).join('')}</div></div><div class="example"><strong lang="${c.lang}">${esc(c.example)}</strong><p>${esc(c.translation)}</p><button class="text-btn" data-do="speak" data-id="${c.id}" data-example="true">▶ 예문 듣기</button></div><details class="bridge"><summary>🌏 두 언어를 연결해 보면</summary><p><b lang="${other.lang}">${esc(other.text)}</b><br>${other.kana?esc(other.kana)+'<br>':''}${esc(other.meaning)}</p><p>${esc(u.bridge)}</p><button class="audio-btn" data-do="speak" data-id="${other.id}">다른 언어 듣기</button></details><div class="lesson-actions"><button class="secondary" data-do="learn-next" data-known="false">🔁 다시 연습할래</button><button class="primary" data-do="learn-next" data-known="true">이해했어! ✓</button></div>`:`<button class="reveal" data-do="reveal">무슨 뜻일까? 잠깐 생각한 뒤 눌러 봐.<br><b>뜻과 이야기 펼치기 ↓</b></button>`}</div>`;}
function nextLesson(known){if(!lesson||!lesson.revealed)return;const c=CARDS.find(c=>c.id===lesson.ids[lesson.index]),r=record(c.id);activeDay();if(known){r.learned=true;if(!state.daily.cards.includes(c.id)){state.daily.cards.push(c.id);state.xp+=10;}if(!r.due||r.due<=Date.now())r.due=Date.now()+DAY;lesson.done++;chime();}else{r.due=Date.now();r.wrong=Math.max(1,r.wrong);}save();renderHeader();lesson.index++;if(lesson.index>=lesson.ids.length){const done=lesson.done;$('#modal-body').innerHTML=`<div class="modal-top"><span class="tag">탐험 완료</span><button class="close" data-do="close" aria-label="닫기">×</button></div><div class="modal-inner result"><div class="result-icon">🎒</div><h2>오늘도 세계가 넓어졌어!</h2><p>${lesson.ids.length}장의 카드를 만났고, ${done}장을 이해했어.<br>다음에는 게임으로 기억을 꺼내 볼까?</p><div class="buttons"><button class="primary" data-do="game" data-mode="meaning">뜻 맞히기 도전 →</button><button class="secondary" data-do="finish">지도 돌아가기</button></div></div>`;celebrate();lesson=null;render();}else{lesson.revealed=false;renderLesson();$('#modal').scrollTop=0;}}
const distractors={1:[10,14,20],2:[10,11,14],3:[14,16,20],4:[10,12,15],5:[10,11,14],6:[13,16,20],7:[13,14,20],8:[5,14,20],9:[5,14,20],10:[1,13,14],11:[1,10,20],12:[1,13,23],13:[7,11,20],14:[7,10,21],15:[5,10,21],16:[3,9,13],17:[7,11,14],18:[5,11,14],19:[6,10,14],20:[1,13,16],21:[10,13,16],22:[6,10,15],23:[10,13,14],24:[7,10,14]};
function startGame(mode,wrongOnly=false){if(!['meaning','build','listen','situation'].includes(mode))return;const pool=langPool();let candidates=wrongOnly?pool.filter(c=>state.records[c.id]?.wrong>0):pool.filter(c=>state.records[c.id]?.learned);if(wrongOnly&&!candidates.length){toast('선택한 언어에는 남은 오답이 없어! 다른 퀘스트에 도전해 봐.');return;}if(!wrongOnly&&candidates.length<4)candidates=pool.filter(c=>c.area===0);const questions=shuffle(candidates).slice(0,5);lesson=null;game={mode,questions,index:0,score:0,answered:false,picks:[],answers:[],tokens:[],options:[],wrongOnly,sessionXP:0};prepareQuestion();openModal();}
function prepareQuestion(){const c=game.questions[game.index];game.answered=false;game.picks=[];game.tokens=shuffle(c.parts.map((text,i)=>({text,i})));game.options=shuffle([c,...distractors[c.unit].map(n=>CARDS.find(v=>v.unit===n&&v.lang===c.lang))]);renderGame();$('#modal').scrollTop=0;}
function renderGame(){if(!game)return;const c=game.questions[game.index],m=game.mode,u=UNITS[c.unit-1];const names={meaning:'뜻 맞히기',build:'문장 조립소',listen:'귀로 찾는 속담',situation:'이럴 땐 이 속담'};$('#modal-body').innerHTML=`<div class="modal-top"><div><span class="tag">${names[m]}</span> <span class="subtle">${game.index+1} / ${game.questions.length} · ⚡ ${game.sessionXP} XP</span></div><button class="close" data-do="close" aria-label="퀴즈 끝내기">×</button></div><div class="modal-inner"><div class="progress"><span style="width:${game.index/game.questions.length*100}%"></span></div><div style="margin-top:20px">${langTag(c)}</div>${m==='meaning'?`<h2 class="question" lang="${c.lang}">${esc(c.text)}</h2>${c.kana&&state.settings.kana?`<p class="kana">${esc(c.kana)}</p>`:''}<button class="audio-btn" data-do="speak" data-id="${c.id}">▶ 들어 보기</button><p class="subtle" style="margin-top:16px">이 문장이 전하는 뜻은?</p>`:m==='situation'?`<h2 class="question">이럴 때 떠올릴 말은?</h2><div class="q-context">${c.icon} ${esc(u.situation)}</div>`:m==='listen'?`<h2 class="question" style="text-align:center">어떤 문장이 들렸어?</h2><button class="question-audio" data-do="speak" data-id="${c.id}" aria-label="문제 음성 듣기">▶</button><div style="text-align:center"><button class="text-btn" data-do="speak" data-id="${c.id}" data-slow="true">🐢 천천히 다시 듣기</button><p class="subtle">재생 버튼을 눌러 봐. 몇 번이든 들어도 돼.</p><button class="text-btn" data-do="listen-fallback">소리가 안 나면 뜻 퀴즈로 풀기</button></div>`:`<h2 class="question">조각을 이어 문장을 완성해!</h2><div class="q-context">${esc(c.meaning)}</div><button class="audio-btn" data-do="speak" data-id="${c.id}">▶ 소리 힌트</button><div id="builder" class="builder"></div><div id="tiles" class="tiles"></div><div class="lesson-actions"><button class="secondary" data-do="clear-tiles">다시 놓기 ↺</button><button id="check-build" class="primary" data-do="check-build" disabled>정답 확인 ✓</button></div>`}${m!=='build'?`<div class="answers">${game.options.map((o,i)=>`<button class="answer" data-do="answer" data-id="${o.id}" lang="${m==='meaning'?'ko':o.lang}"><span class="key">${i+1}</span><span>${esc(m==='meaning'?o.meaning:o.text)}${m!=='meaning'&&o.kana&&state.settings.kana?`<small class="kana" style="display:block;font-size:11px">${esc(o.kana)}</small>`:''}</span></button>`).join('')}</div>`:''}<div id="feedback" aria-live="polite"></div></div>`;if(m==='build')renderTiles();}
function renderTiles(){if(!game)return;$('#builder').innerHTML=game.picks.length?game.picks.map((n,i)=>`<button class="tile" data-do="remove-tile" data-index="${i}" lang="${game.questions[game.index].lang}" aria-label="${esc(game.tokens[n].text)} 빼기">${esc(game.tokens[n].text)}</button>`).join(''):'<span class="hint">아래 조각을 순서대로 눌러 여기에 놓아 줘.</span>';$('#tiles').innerHTML=game.tokens.map((t,i)=>`<button class="tile" data-do="pick-tile" data-index="${i}" ${game.picks.includes(i)?'disabled':''} lang="${game.questions[game.index].lang}">${esc(t.text)}</button>`).join('');$('#check-build').disabled=game.picks.length!==game.tokens.length;}
function answer(correct,chosenId){if(!game||game.answered)return;game.answered=true;const c=game.questions[game.index],r=record(c.id);activeDay();state.totalAnswers++;state.daily.answers++;if(correct){game.score++;game.sessionXP+=15;state.xp+=15;state.correctAnswers++;r.learned=true;r.hits++;r.wrong=0;r.lastCorrect=dateKey();r.due=Date.now()+[1,3,7][Math.min(2,r.hits-1)]*DAY;chime();}else{r.wrong++;r.due=Date.now();chime(false);}game.answers.push({id:c.id,correct});save();renderHeader();if(game.mode!=='build'){document.querySelectorAll('.answer').forEach(b=>{b.disabled=true;b.classList.add(b.dataset.id===c.id?'correct':b.dataset.id===chosenId?'wrong':'dim')})}else{$('#modal-body').querySelectorAll('.tile,[data-do="clear-tiles"],[data-do="check-build"]').forEach(b=>b.disabled=true);}
 $('#feedback').innerHTML=`<div class="feedback ${correct?'':'wrong'}"><strong>${correct?'✨ 정답! 기억이 한 칸 자랐어.':'🌱 괜찮아. 지금 배우면 돼!'}</strong><p lang="${c.lang}"><b>${esc(c.text)}</b></p>${c.kana&&state.settings.kana?`<p lang="ja">${esc(c.kana)}</p>`:''}<p>${esc(c.meaning)}</p>${game.mode==='situation'?`<p class="subtle">${esc(UNITS[c.unit-1].bridge)}</p>`:''}<button class="audio-btn" data-do="speak" data-id="${c.id}">▶ 정답 듣기</button> <button class="primary" data-do="next-question">${game.index+1===game.questions.length?'결과 보기':'다음 문제'} →</button></div>`;
 $('#feedback').scrollIntoView?.({behavior:'smooth',block:'nearest'});
}
function nextQuestion(){if(!game?.answered)return;game.index++;if(game.index<game.questions.length){prepareQuestion();return;}const result=game;game=null;state.rounds++;if(result.score===result.questions.length)state.perfect++;save();render();$('#modal-body').innerHTML=`<div class="modal-top"><span class="tag">QUEST COMPLETE</span><button class="close" data-do="close" aria-label="결과 닫기">×</button></div><div class="modal-inner result"><div class="result-icon">${result.score===result.questions.length?'🏆':'🎉'}</div><h2>${result.score===result.questions.length?'모든 문장을 잡았어!':'한 판 완료! 잘 해냈어.'}</h2><p>맞힌 것은 실력으로, 틀린 것은 다음 배움으로.</p><div class="result-score">${result.score} <small>/ ${result.questions.length} 정답</small></div><span class="tag">+${result.sessionXP} XP 획득</span><div class="buttons"><button class="primary" data-do="game" data-mode="${result.mode}">한 판 더 →</button><button class="secondary" data-do="finish">퀘스트로 돌아가기</button></div><div class="result-list">${result.answers.map(a=>{const c=CARDS.find(c=>c.id===a.id);return `<button data-do="detail" data-id="${c.id}">${a.correct?'✅':'🔁'} <span lang="${c.lang}">${esc(c.text)}</span><span class="subtle" style="display:block;margin-left:24px">${esc(c.meaning)} · 카드 보기 ↗</span></button>`}).join('')}</div></div>`;$('#modal').scrollTop=0;celebrate();}
function loadVoices(){voices=window.speechSynthesis?.getVoices()||[];if(view==='settings')fillVoices();}
function fillVoices(){for(const [id,lang,key] of [['en-voice','en','englishVoice'],['ja-voice','ja','japaneseVoice']]){const el=$('#'+id);if(!el)continue;el.innerHTML='<option value="">기기에 맞게 자동 선택</option>'+voices.filter(v=>v.lang.toLowerCase().startsWith(lang)).map(v=>`<option value="${esc(v.voiceURI)}" ${state.settings[key]===v.voiceURI?'selected':''}>${esc(v.name)} (${esc(v.lang)})</option>`).join('');}const status=$('#voice-status');if(status)status.textContent=!('speechSynthesis'in window)?'이 브라우저는 읽어주기를 지원하지 않아. Chrome 또는 Safari에서 열어 줘.':`이 기기의 목소리: 영어 ${voices.filter(v=>v.lang.startsWith('en')).length}개 · 일본어 ${voices.filter(v=>v.lang.startsWith('ja')).length}개. 소리가 없으면 기기의 텍스트 읽어주기 설정에서 해당 언어를 추가하고 다시 열어 줘.`;}
function speak(id,slow=false,example=false){const c=CARDS.find(v=>v.id===id);if(!c)return;if(!window.speechSynthesis||!window.SpeechSynthesisUtterance){toast('이 브라우저에서는 듣기를 지원하지 않아. Chrome 또는 Safari로 열어 줘.');return;}loadVoices();const list=voices.filter(v=>v.lang.toLowerCase().startsWith(c.lang));if(voices.length&&!list.length){toast(`${c.lang==='en'?'영어':'일본어'} 음성이 없어. 기기 읽어주기 설정에서 언어를 추가해 줘.`);return;}window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(example?c.example:c.kana||c.text);u.lang=c.lang==='en'?'en-US':'ja-JP';u.rate=slow?.65:.88;u.pitch=1;const preferred=state.settings[c.lang==='en'?'englishVoice':'japaneseVoice'];u.voice=list.find(v=>v.voiceURI===preferred)||list.find(v=>v.lang===u.lang)||list[0]||null;u.onstart=()=>{activeDay();if(!state.daily.listens.includes(id))state.daily.listens.push(id);save();renderHeader();};u.onerror=e=>{if(!['interrupted','canceled'].includes(e.error))toast('소리가 나오지 않으면 미디어 음량과 기기 읽어주기 언어를 확인해 줘.');};u.onend=()=>{speechUtterance=null;};speechUtterance=u;window.speechSynthesis.speak(u);}
async function install(){if(installPrompt){await installPrompt.prompt();const result=await installPrompt.userChoice;installPrompt=null;if(result.outcome==='accepted')toast('홈 화면에서 속담 탐험을 찾아 줘!');return;}if(window.matchMedia?.('(display-mode: standalone)').matches){toast('이미 앱 화면으로 사용하고 있어!');return;}$('#modal-body').innerHTML=`<div class="modal-top"><span class="tag">앱으로 설치하기</span><button class="close" data-do="close" aria-label="닫기">×</button></div><div class="modal-inner"><h2>홈 화면에서 바로 모험 시작!</h2><div class="callout"><strong>안드로이드 · Chrome</strong><br>오른쪽 위 ⋮ 메뉴 → ‘앱 설치’ 또는 ‘홈 화면에 추가’<br><br><strong>아이폰 · Safari</strong><br>공유 버튼 → ‘홈 화면에 추가’<br><br><strong>PC · Chrome / Edge</strong><br>주소창의 설치 아이콘 또는 브라우저 메뉴의 설치 항목</div><p class="subtle">카카오톡 안에서 열었다면 메뉴에서 다른 브라우저로 열어 줘. 한 번 접속해 자료가 저장되면 대부분의 학습 기능은 인터넷 없이도 쓸 수 있어. 듣기는 기기 음성 설정에 따라 연결이 필요해.</p></div>`;openModal();}
function exportState(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`proverb-quest-${dateKey()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),5000);toast('기록 파일을 내려받았어. 다른 기기에서 가져올 수 있어.');}
function toggleStar(id){if(!ids.has(id))return;state.stars=state.stars.includes(id)?state.stars.filter(v=>v!==id):[...state.stars,id];save();}
document.addEventListener('click',e=>{const b=e.target.closest('[data-do]');if(!b||b.disabled)return;const a=b.dataset.do;switch(a){
 case'navigate':if(b.dataset.view==='cards')collection.area=null;go(b.dataset.view);break;
 case'language':state.settings.language=b.dataset.value;save();render();break;
 case'area':collection.area=Number(b.dataset.area);collection.query='';collection.filter='all';go('cards');break;
 case'all-areas':collection.area=null;render();break;
 case'area-learn':startLesson(langPool().filter(c=>c.area===Number(b.dataset.area)).map(c=>c.id),AREAS[Number(b.dataset.area)].name);break;
 case'daily':dailyStart();break;
 case'detail':startLesson([b.dataset.id],'속담 카드');break;
 case'review':startLesson(dueCards().sort((a,b)=>state.records[a.id].due-state.records[b.id].due).slice(0,6).map(c=>c.id),'다시 만나는 문장');break;
 case'star':toggleStar(b.dataset.id);$('#card-grid').innerHTML=cardGrid();break;
 case'lesson-star':toggleStar(b.dataset.id);renderLesson();break;
 case'show-pron':state.settings.pron=true;save();renderLesson();break;
 case'reveal':if(lesson){lesson.revealed=true;renderLesson();}break;
 case'learn-next':nextLesson(b.dataset.known==='true');break;
 case'speak':speak(b.dataset.id,b.dataset.slow==='true',b.dataset.example==='true');break;
 case'stop-speech':window.speechSynthesis?.cancel();break;
 case'close':closeModal();render();break;
 case'finish':closeModal();render();break;
 case'game':startGame(b.dataset.mode);break;
 case'wrong-game':startGame('meaning',true);break;
 case'answer':if(game)answer(b.dataset.id===game.questions[game.index].id,b.dataset.id);break;
 case'next-question':nextQuestion();break;
 case'pick-tile':if(game&&!game.answered&&!game.picks.includes(Number(b.dataset.index))){game.picks.push(Number(b.dataset.index));renderTiles();}break;
 case'remove-tile':if(game&&!game.answered){game.picks.splice(Number(b.dataset.index),1);renderTiles();}break;
 case'clear-tiles':if(game&&!game.answered){game.picks=[];renderTiles();}break;
 case'check-build':if(game&&game.picks.length===game.tokens.length){const c=game.questions[game.index];answer(game.picks.map(i=>game.tokens[i].text).join('\u0000')===c.parts.join('\u0000'));}break;
 case'listen-fallback':if(game&&!game.answered){window.speechSynthesis?.cancel();game.mode='meaning';renderGame();}break;
 case'toggle':if(['sound','kana','pron'].includes(b.dataset.key)){state.settings[b.dataset.key]=!state.settings[b.dataset.key];save();render();}break;
 case'install':install().catch(()=>toast('브라우저 메뉴의 홈 화면에 추가를 사용해 줘.'));break;
 case'export':exportState();break;
 case'import':$('#import-file')?.click();break;
 case'reset':if(confirm('모든 학습 기록을 지울까? 이 작업은 되돌릴 수 없어.')){state=fresh();save();render();toast('새로운 탐험을 시작해 보자!');}break;
 }});
document.addEventListener('input',e=>{if(e.target.id==='search'){collection.query=e.target.value;$('#card-grid').innerHTML=cardGrid();}});
document.addEventListener('change',async e=>{if(e.target.id==='card-filter'){collection.filter=e.target.value;$('#card-grid').innerHTML=cardGrid();}if(e.target.id==='en-voice'||e.target.id==='ja-voice'){state.settings[e.target.id==='en-voice'?'englishVoice':'japaneseVoice']=e.target.value;save();}if(e.target.id==='import-file'){const f=e.target.files[0];if(!f)return;if(f.size>2*1024*1024){toast('기록 파일이 너무 커. 2MB 이하의 기록 파일을 골라 줘.');return;}try{const imported=sanitize(JSON.parse(await f.text()));if(confirm('현재 기록을 이 파일의 기록으로 바꿀까?')){state=imported;save();render();toast('학습 기록을 가져왔어!');}}catch{toast('학습 기록 파일을 읽지 못했어. 이 앱에서 내려받은 JSON 파일인지 확인해 줘.');}e.target.value='';}});
document.addEventListener('keydown',e=>{if(!$('#modal').open||!game||game.answered||['INPUT','SELECT','TEXTAREA'].includes(e.target.tagName))return;if(['1','2','3','4'].includes(e.key)&&game.mode!=='build'){const b=$('#modal-body').querySelectorAll('.answer')[Number(e.key)-1];b?.click();}});
window.addEventListener('hashchange',()=>{const next=location.hash.slice(1);if(navs.some(n=>n[0]===next)){closeModal();view=next;render();}});
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;});
window.addEventListener('appinstalled',()=>{installPrompt=null;toast('설치 완료! 홈 화면에서 다시 만나.');});
window.addEventListener('pageshow',()=>{ensureDay();renderHeader();});
window.speechSynthesis?.addEventListener('voiceschanged',loadVoices);
if('serviceWorker'in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js',{scope:'./'}).catch(()=>{}));}
loadVoices();render();if(!storageOK)setTimeout(()=>toast('이 브라우저에서는 기록을 읽거나 저장할 수 없어. 설정에서 기록을 내려받아 줘.'),300);
})();
